// SPDX-FileCopyrightText: 2026 The Azerothcore-Single-Player contributors
// SPDX-License-Identifier: AGPL-3.0-or-later
// Catálogo de parámetros candidatos a la pantalla de configuración del panel
// (GM nivel 3+). Derivado de REFERENCIA_CONFIG_PANEL.md y contrastado con los
// .conf.dist de las versiones fijadas: cada fila agrupada del documento
// ("7 claves, una por calidad", "N claves") se expande en una clave real.
// `min`/`max` son aproximaciones prácticas
// de los rangos documentados (p. ej. "> 0" se trata como suelo 0), no cotas
// exactas del core.

export const CATEGORIES = [
  {
    id: 'rates-combat',
    label: 'Tasas de combate y regeneración',
    group: 'core',
    module: null,
    file: 'worldserver.conf',
    params: [
      { key: 'Rate.Health', default: '1.0', type: 'float', min: 0, max: null, risk: 'low', description: 'Multiplicador de la vida máxima de personajes y criaturas.' },
      { key: 'Rate.Mana', default: '1.0', type: 'float', min: 0, max: null, risk: 'low', description: 'Multiplicador del maná máximo.' },
      { key: 'Rate.Rage.Income', default: '1.0', type: 'float', min: null, max: null, risk: 'low', description: 'Multiplicador de generación de furia.' },
      { key: 'Rate.Rage.Loss', default: '1.0', type: 'float', min: 0, max: null, risk: 'low', description: 'Multiplicador de pérdida de furia.' },
      { key: 'Rate.RunicPower.Income', default: '1.0', type: 'float', min: null, max: null, risk: 'low', description: 'Multiplicador de generación de poder rúnico.' },
      { key: 'Rate.RunicPower.Loss', default: '1', type: 'float', min: 0, max: null, risk: 'low', description: 'Multiplicador de pérdida de poder rúnico.' },
      { key: 'Rate.Focus', default: '1.0', type: 'float', min: null, max: null, risk: 'low', description: 'Multiplicador de generación de concentración (cazadores).' },
      { key: 'Rate.Energy', default: '1.0', type: 'float', min: null, max: null, risk: 'low', description: 'Multiplicador de generación de energía (pícaros y druidas felinos).' },
      { key: 'Rate.MissChanceMultiplier.TargetCreature', default: '11.0', type: 'float', min: null, max: null, risk: 'medium', description: 'Afecta el ritmo de combate PvE globalmente.' },
      { key: 'Rate.MissChanceMultiplier.TargetPlayer', default: '7.0', type: 'float', min: null, max: null, risk: 'medium', description: 'Afecta el ritmo de combate PvP globalmente.' },
      { key: 'Rate.MissChanceMultiplier.OnlyAffectsPlayer', default: 'false', type: 'bool', min: null, max: null, risk: 'low', description: 'Si el multiplicador de fallo sólo se aplica a jugadores.' },
      { key: 'Rate.Talent', default: '1.0', type: 'float', min: 0, max: null, risk: 'low', description: 'Multiplicador de puntos de talento obtenidos.' },
      { key: 'Rate.Talent.Pet', default: '1.0', type: 'float', min: 0, max: null, risk: 'low', description: 'Multiplicador de puntos de talento de mascota.' },
      { key: 'Rate.MoveSpeed.Player', default: '1.0', type: 'float', min: 0, max: null, risk: 'medium', description: 'Valores extremos rompen la sensación de juego y pueden facilitar exploits de movimiento.' },
      { key: 'Rate.MoveSpeed.NPC', default: '1.0', type: 'float', min: 0, max: null, risk: 'medium', description: 'Ídem, del lado de las criaturas.' },
    ],
  },
  {
    id: 'rates-loot-economy',
    label: 'Tasas de botín y economía',
    group: 'core',
    module: null,
    file: 'worldserver.conf',
    params: [
      { key: 'Rate.Drop.Item.Poor', default: '1.0', type: 'float', min: 0, max: null, risk: 'low', description: 'Multiplicador de aparición de objetos de calidad Pobre.' },
      { key: 'Rate.Drop.Item.Normal', default: '1.0', type: 'float', min: 0, max: null, risk: 'low', description: 'Multiplicador de aparición de objetos de calidad Normal.' },
      { key: 'Rate.Drop.Item.Uncommon', default: '1.0', type: 'float', min: 0, max: null, risk: 'low', description: 'Multiplicador de aparición de objetos de calidad Excepcional.' },
      { key: 'Rate.Drop.Item.Rare', default: '1.0', type: 'float', min: 0, max: null, risk: 'low', description: 'Multiplicador de aparición de objetos de calidad Rara.' },
      { key: 'Rate.Drop.Item.Epic', default: '1.0', type: 'float', min: 0, max: null, risk: 'low', description: 'Multiplicador de aparición de objetos de calidad Épica.' },
      { key: 'Rate.Drop.Item.Legendary', default: '1.0', type: 'float', min: 0, max: null, risk: 'low', description: 'Multiplicador de aparición de objetos de calidad Legendaria.' },
      { key: 'Rate.Drop.Item.Artifact', default: '1.0', type: 'float', min: 0, max: null, risk: 'low', description: 'Multiplicador de aparición de objetos de calidad Artefacto.' },
      { key: 'Rate.Drop.Item.Referenced', default: '1.0', type: 'float', min: 0, max: null, risk: 'low', description: 'Multiplicador de aparición de objetos referenciados en tablas de botín.' },
      { key: 'Rate.Drop.Item.ReferencedAmount', default: '1.0', type: 'float', min: 0, max: null, risk: 'low', description: 'Multiplicador de la cantidad de objetos referenciados.' },
      { key: 'Rate.Drop.Item.GroupAmount', default: '1.0', type: 'float', min: 0, max: null, risk: 'low', description: 'Multiplicador de la cantidad de objetos por grupo.' },
      { key: 'Rate.Drop.Money', default: '1.0', type: 'float', min: 0, max: null, risk: 'medium', description: 'Impacto económico directo: oro que sueltan las criaturas.' },
      { key: 'Rate.RewardQuestMoney', default: '1.0', type: 'float', min: 0, max: null, risk: 'medium', description: 'Impacto económico directo: oro entregado como recompensa de misión.' },
      { key: 'Rate.RewardBonusMoney', default: '1.0', type: 'float', min: 0, max: null, risk: 'medium', description: 'Impacto económico directo.' },
      { key: 'Rate.RepairCost', default: '1.0', type: 'float', min: 0, max: null, risk: 'low', description: 'Coste de reparar equipo con un armero.' },
      { key: 'Rate.SellValue.Item.Poor', default: '1.0', type: 'float', min: 0, max: null, risk: 'medium', description: 'Cuánto dan los vendedores por objetos de calidad Pobre.' },
      { key: 'Rate.SellValue.Item.Normal', default: '1.0', type: 'float', min: 0, max: null, risk: 'medium', description: 'Cuánto dan los vendedores por objetos de calidad Normal.' },
      { key: 'Rate.SellValue.Item.Uncommon', default: '1.0', type: 'float', min: 0, max: null, risk: 'medium', description: 'Cuánto dan los vendedores por objetos de calidad Excepcional.' },
      { key: 'Rate.SellValue.Item.Rare', default: '1.0', type: 'float', min: 0, max: null, risk: 'medium', description: 'Cuánto dan los vendedores por objetos de calidad Rara.' },
      { key: 'Rate.SellValue.Item.Epic', default: '1.0', type: 'float', min: 0, max: null, risk: 'medium', description: 'Cuánto dan los vendedores por objetos de calidad Épica.' },
      { key: 'Rate.SellValue.Item.Legendary', default: '1.0', type: 'float', min: 0, max: null, risk: 'medium', description: 'Cuánto dan los vendedores por objetos de calidad Legendaria.' },
      { key: 'Rate.SellValue.Item.Artifact', default: '1.0', type: 'float', min: 0, max: null, risk: 'medium', description: 'Cuánto dan los vendedores por objetos de calidad Artefacto.' },
      { key: 'Rate.SellValue.Item.Heirloom', default: '1.0', type: 'float', min: 0, max: null, risk: 'medium', description: 'Cuánto dan los vendedores por objetos de calidad Herencia.' },
      { key: 'Rate.BuyValue.Item.Poor', default: '1.0', type: 'float', min: 0, max: null, risk: 'medium', description: 'Cuánto cuesta comprar objetos de calidad Pobre a un vendedor.' },
      { key: 'Rate.BuyValue.Item.Normal', default: '1.0', type: 'float', min: 0, max: null, risk: 'medium', description: 'Cuánto cuesta comprar objetos de calidad Normal a un vendedor.' },
      { key: 'Rate.BuyValue.Item.Uncommon', default: '1.0', type: 'float', min: 0, max: null, risk: 'medium', description: 'Cuánto cuesta comprar objetos de calidad Excepcional a un vendedor.' },
      { key: 'Rate.BuyValue.Item.Rare', default: '1.0', type: 'float', min: 0, max: null, risk: 'medium', description: 'Cuánto cuesta comprar objetos de calidad Rara a un vendedor.' },
      { key: 'Rate.BuyValue.Item.Epic', default: '1.0', type: 'float', min: 0, max: null, risk: 'medium', description: 'Cuánto cuesta comprar objetos de calidad Épica a un vendedor.' },
      { key: 'Rate.BuyValue.Item.Legendary', default: '1.0', type: 'float', min: 0, max: null, risk: 'medium', description: 'Cuánto cuesta comprar objetos de calidad Legendaria a un vendedor.' },
      { key: 'Rate.BuyValue.Item.Artifact', default: '1.0', type: 'float', min: 0, max: null, risk: 'medium', description: 'Cuánto cuesta comprar objetos de calidad Artefacto a un vendedor.' },
      { key: 'Rate.BuyValue.Item.Heirloom', default: '1.0', type: 'float', min: 0, max: null, risk: 'medium', description: 'Cuánto cuesta comprar objetos de calidad Herencia a un vendedor.' },
      { key: 'Rate.Auction.Time', default: '1.0', type: 'float', min: 0, max: null, risk: 'low', description: 'Multiplicador de la duración de las subastas.' },
      { key: 'Rate.Auction.Deposit', default: '1.0', type: 'float', min: 0, max: null, risk: 'medium', description: 'Afecta el coste de publicar en subasta.' },
      { key: 'Rate.Auction.Cut', default: '1.0', type: 'float', min: 0, max: null, risk: 'medium', description: 'Afecta la comisión de la casa de subastas.' },
    ],
  },
  {
    id: 'rates-experience',
    label: 'Tasas de experiencia',
    group: 'core',
    module: null,
    file: 'worldserver.conf',
    params: [
      { key: 'Rate.XP.Kill', default: '1.0', type: 'float', min: 0, max: null, risk: 'low', description: 'Multiplicador de experiencia por matar criaturas.' },
      { key: 'Rate.XP.BattlegroundKillAV', default: '1.0', type: 'float', min: 0, max: null, risk: 'low', description: 'Multiplicador de experiencia por victoria en Valle de Alterac.' },
      { key: 'Rate.XP.BattlegroundKillWSG', default: '1.0', type: 'float', min: 0, max: null, risk: 'low', description: 'Multiplicador de experiencia por victoria en Cañón de Guerrasangre.' },
      { key: 'Rate.XP.BattlegroundKillAB', default: '1.0', type: 'float', min: 0, max: null, risk: 'low', description: 'Multiplicador de experiencia por victoria en Cuenca de Arathi.' },
      { key: 'Rate.XP.BattlegroundKillEOTS', default: '1.0', type: 'float', min: 0, max: null, risk: 'low', description: 'Multiplicador de experiencia por victoria en Ojo de la Tormenta.' },
      { key: 'Rate.XP.BattlegroundKillSOTA', default: '1.0', type: 'float', min: 0, max: null, risk: 'low', description: 'Multiplicador de experiencia por victoria en Asalto a la Playa de los Antiguos.' },
      { key: 'Rate.XP.BattlegroundKillIC', default: '1.0', type: 'float', min: 0, max: null, risk: 'low', description: 'Multiplicador de experiencia por victoria en Isla de la Conquista.' },
      { key: 'Rate.XP.Quest', default: '1.0', type: 'float', min: 0, max: null, risk: 'low', description: 'Multiplicador de experiencia de misiones.' },
      { key: 'Rate.XP.Quest.DF', default: '1.0', type: 'float', min: 0, max: null, risk: 'low', description: 'Multiplicador de experiencia de misiones del buscador de mazmorras.' },
      { key: 'Rate.XP.Explore', default: '1.0', type: 'float', min: 0, max: null, risk: 'low', description: 'Multiplicador de experiencia por explorar zonas.' },
      { key: 'Rate.XP.Pet', default: '1.0', type: 'float', min: 0, max: null, risk: 'low', description: 'Multiplicador de experiencia de mascotas.' },
      { key: 'Rate.Pet.LevelXP', default: '0.05', type: 'float', min: 0, max: null, risk: 'low', description: 'Multiplicador de experiencia necesaria para subir de nivel a una mascota.' },
      { key: 'Rate.XP.BattlegroundBonus', default: '1.0', type: 'float', min: 0, max: null, risk: 'low', description: 'Multiplicador de experiencia bonus en campos de batalla.' },
    ],
  },
  {
    id: 'rates-reputation',
    label: 'Tasas de reputación',
    group: 'core',
    module: null,
    file: 'worldserver.conf',
    params: [
      { key: 'Rate.Reputation.Gain', default: '1.0', type: 'float', min: 0, max: null, risk: 'low', description: 'Multiplicador general de ganancia de reputación.' },
      { key: 'Rate.Reputation.Gain.AB', default: '1.0', type: 'float', min: 0, max: null, risk: 'low', description: 'Multiplicador de reputación en Cuenca de Arathi.' },
      { key: 'Rate.Reputation.Gain.AV', default: '1.0', type: 'float', min: 0, max: null, risk: 'low', description: 'Multiplicador de reputación en Valle de Alterac.' },
      { key: 'Rate.Reputation.Gain.WSG', default: '1.0', type: 'float', min: 0, max: null, risk: 'low', description: 'Multiplicador de reputación en Cañón de Guerrasangre.' },
      { key: 'Rate.Reputation.LowLevel.Kill', default: '1.0', type: 'float', min: 0, max: null, risk: 'low', description: 'Multiplicador de reputación por matar criaturas de bajo nivel.' },
      { key: 'Rate.Reputation.LowLevel.Quest', default: '1.0', type: 'float', min: 0, max: null, risk: 'low', description: 'Multiplicador de reputación por misiones de bajo nivel.' },
      { key: 'Rate.Reputation.RecruitAFriendBonus', default: '0.1', type: 'float', min: 0, max: null, risk: 'low', description: 'Bonus de reputación del programa Recluta a un Amigo.' },
    ],
  },
  {
    id: 'rates-creature',
    label: 'Tasas de daño y HP de criaturas',
    group: 'core',
    module: null,
    file: 'worldserver.conf',
    params: [
      { key: 'Rate.Creature.Normal.Damage', default: '1.0', type: 'float', min: 0, max: null, risk: 'medium', description: 'Afecta la dificultad general de todo mob normal.' },
      { key: 'Rate.Creature.Normal.HP', default: '1.0', type: 'float', min: 0, max: null, risk: 'medium', description: 'Afecta la dificultad general de todo mob normal.' },
      { key: 'Rate.Creature.Normal.SpellDamage', default: '1.0', type: 'float', min: 0, max: null, risk: 'medium', description: 'Afecta la dificultad general de todo mob normal.' },
      { key: 'Rate.Creature.Elite.Elite.Damage', default: '1.0', type: 'float', min: 0, max: null, risk: 'medium', description: 'Daño de criaturas de élite.' },
      { key: 'Rate.Creature.Elite.Elite.HP', default: '1.0', type: 'float', min: 0, max: null, risk: 'medium', description: 'Vida de criaturas de élite.' },
      { key: 'Rate.Creature.Elite.Elite.SpellDamage', default: '1.0', type: 'float', min: 0, max: null, risk: 'medium', description: 'Daño de hechizo de criaturas de élite.' },
      { key: 'Rate.Creature.Elite.RAREELITE.Damage', default: '1.0', type: 'float', min: 0, max: null, risk: 'medium', description: 'Daño de criaturas de élite rara.' },
      { key: 'Rate.Creature.Elite.RAREELITE.HP', default: '1.0', type: 'float', min: 0, max: null, risk: 'medium', description: 'Vida de criaturas de élite rara.' },
      { key: 'Rate.Creature.Elite.RAREELITE.SpellDamage', default: '1.0', type: 'float', min: 0, max: null, risk: 'medium', description: 'Daño de hechizo de criaturas de élite rara.' },
      { key: 'Rate.Creature.Elite.WORLDBOSS.Damage', default: '1.0', type: 'float', min: 0, max: null, risk: 'medium', description: 'Daño de jefes de mundo.' },
      { key: 'Rate.Creature.Elite.WORLDBOSS.HP', default: '1.0', type: 'float', min: 0, max: null, risk: 'medium', description: 'Vida de jefes de mundo.' },
      { key: 'Rate.Creature.Elite.WORLDBOSS.SpellDamage', default: '1.0', type: 'float', min: 0, max: null, risk: 'medium', description: 'Daño de hechizo de jefes de mundo.' },
      { key: 'Rate.Creature.Elite.RARE.Damage', default: '1.0', type: 'float', min: 0, max: null, risk: 'medium', description: 'Daño de criaturas raras.' },
      { key: 'Rate.Creature.Elite.RARE.HP', default: '1.0', type: 'float', min: 0, max: null, risk: 'medium', description: 'Vida de criaturas raras.' },
      { key: 'Rate.Creature.Elite.RARE.SpellDamage', default: '1.0', type: 'float', min: 0, max: null, risk: 'medium', description: 'Daño de hechizo de criaturas raras.' },
      { key: 'Rate.Creature.Aggro', default: '1.0', type: 'float', min: 0, max: null, risk: 'low', description: 'Radio de detección de criaturas.' },
    ],
  },
  {
    id: 'rates-rest-durability',
    label: 'Tasas de descanso, caída y cadáveres',
    group: 'core',
    module: null,
    file: 'worldserver.conf',
    params: [
      { key: 'Rate.Rest.InGame', default: '1.0', type: 'float', min: 0, max: null, risk: 'low', description: 'Multiplicador de recuperación de descanso jugando.' },
      { key: 'Rate.Rest.Offline.InTavernOrCity', default: '1.0', type: 'float', min: 0, max: null, risk: 'low', description: 'Multiplicador de descanso desconectado en taberna o ciudad.' },
      { key: 'Rate.Rest.Offline.InWilderness', default: '1.0', type: 'float', min: 0, max: null, risk: 'low', description: 'Multiplicador de descanso desconectado fuera de ciudad.' },
      { key: 'Rate.Rest.MaxBonus', default: '1.5', type: 'float', min: 0, max: null, risk: 'low', description: 'Tope del bonus de descanso acumulado.' },
      { key: 'Rate.Damage.Fall', default: '1.0', type: 'float', min: 0, max: null, risk: 'low', description: 'Multiplicador de daño por caída.' },
      { key: 'Rate.Corpse.Decay.Looted', default: '0.5', type: 'float', min: 0, max: null, risk: 'low', description: 'Multiplicador de tiempo hasta que desaparece un cadáver ya saqueado.' },
      { key: 'DurabilityLoss.OnDeath', default: '10.0', type: 'float', min: 0, max: 100, risk: 'low', description: 'Porcentaje de durabilidad perdida al morir.' },
      { key: 'DurabilityLoss.OnSpiritResurrect', default: '25.0', type: 'float', min: 0, max: 100, risk: 'low', description: 'Porcentaje de durabilidad perdida al resucitar como espíritu.' },
      { key: 'DurabilityLossChance.Damage', default: '0.5', type: 'float', min: 0, max: null, risk: 'low', description: 'Probabilidad de perder durabilidad al recibir daño.' },
      { key: 'DurabilityLossChance.Absorb', default: '0.5', type: 'float', min: 0, max: null, risk: 'low', description: 'Probabilidad de perder durabilidad al absorber daño.' },
      { key: 'DurabilityLossChance.Parry', default: '0.05', type: 'float', min: 0, max: null, risk: 'low', description: 'Probabilidad de perder durabilidad al parar un golpe.' },
      { key: 'DurabilityLossChance.Block', default: '0.05', type: 'float', min: 0, max: null, risk: 'low', description: 'Probabilidad de perder durabilidad al bloquear un golpe.' },
    ],
  },
  {
    id: 'rates-pvp-misc',
    label: 'Tasas de PvP y misceláneo',
    group: 'core',
    module: null,
    file: 'worldserver.conf',
    params: [
      { key: 'Rate.Honor', default: '1.0', type: 'float', min: 0, max: null, risk: 'medium', description: 'Progresión PvP: multiplicador de honor.' },
      { key: 'Rate.ArenaPoints', default: '1.0', type: 'float', min: 0, max: null, risk: 'medium', description: 'Multiplicador de puntos de arena.' },
      { key: 'Rate.ArenaPoints2v2', default: '0.76', type: 'float', min: 0, max: null, risk: 'medium', description: 'Multiplicador de puntos de arena 2v2.' },
      { key: 'Rate.ArenaPoints3v3', default: '0.88', type: 'float', min: 0, max: null, risk: 'medium', description: 'Multiplicador de puntos de arena 3v3.' },
      { key: 'Rate.InstanceResetTime', default: '1.0', type: 'float', min: 0, max: null, risk: 'low', description: 'Multiplicador del tiempo de reseteo de instancias.' },
    ],
  },
  {
    id: 'skills-professions',
    label: 'Habilidades y profesiones',
    group: 'core',
    module: null,
    file: 'worldserver.conf',
    params: [
      { key: 'MaxPrimaryTradeSkill', default: '2', type: 'int', min: 0, max: 11, risk: 'medium', description: 'Máximo de profesiones primarias que puede aprender un personaje. Cocina, pesca y primeros auxilios son secundarias y no cuentan para este límite.' },
      { key: 'AlwaysMaxSkillForLevel', default: 'false', type: 'bool', min: null, max: null, risk: 'medium', description: 'Al iniciar sesión o subir de nivel, lleva automáticamente al máximo permitido las habilidades del personaje, incluidas las profesiones. Cambia la progresión normal de habilidades.' },
      { key: 'SkillChance.Prospecting', default: 'false', type: 'bool', min: null, max: null, risk: 'low', description: 'Permite subir habilidad al prospectar menas.' },
      { key: 'SkillChance.Milling', default: 'false', type: 'bool', min: null, max: null, risk: 'low', description: 'Permite subir habilidad al moler hierbas.' },
      { key: 'Rate.Skill.Discovery', default: '1.0', type: 'float', min: 0, max: null, risk: 'low', description: 'Multiplicador de la probabilidad de descubrir recetas mediante profesiones.' },
      { key: 'SkillGain.Crafting', default: '1', type: 'int', min: 0, max: null, risk: 'low', description: 'Puntos de habilidad obtenidos al fabricar objetos.' },
      { key: 'SkillGain.Gathering', default: '1', type: 'int', min: 0, max: null, risk: 'low', description: 'Puntos de habilidad obtenidos al recolectar, minar, desollar o pescar.' },
      { key: 'SkillGain.Defense', default: '1', type: 'int', min: 0, max: null, risk: 'low', description: 'Puntos de habilidad de defensa obtenidos en combate.' },
      { key: 'SkillGain.Weapon', default: '1', type: 'int', min: 0, max: null, risk: 'low', description: 'Puntos de habilidad de armas obtenidos en combate.' },
      { key: 'SkillChance.Orange', default: '100', type: 'int', min: 0, max: 100, risk: 'low', description: 'Probabilidad de ganar un punto al crear una receta naranja.' },
      { key: 'SkillChance.Yellow', default: '75', type: 'int', min: 0, max: 100, risk: 'low', description: 'Probabilidad de ganar un punto al crear una receta amarilla.' },
      { key: 'SkillChance.Green', default: '25', type: 'int', min: 0, max: 100, risk: 'low', description: 'Probabilidad de ganar un punto al crear una receta verde.' },
      { key: 'SkillChance.Grey', default: '0', type: 'int', min: 0, max: 100, risk: 'low', description: 'Probabilidad de ganar un punto al crear una receta gris.' },
      { key: 'SkillChance.MiningSteps', default: '0', type: 'int', min: 0, max: 100, risk: 'low', description: 'Reduce escalonadamente la probabilidad de subir minería según aumenta la habilidad. 0 conserva el comportamiento normal.' },
      { key: 'SkillChance.SkinningSteps', default: '0', type: 'int', min: 0, max: 100, risk: 'low', description: 'Reduce escalonadamente la probabilidad de subir desuello según aumenta la habilidad. 0 conserva el comportamiento normal.' },
    ],
  },
  {
    id: 'gm-security',
    label: 'GM y seguridad',
    group: 'core',
    module: null,
    file: 'worldserver.conf',
    params: [
      { key: 'GM.StartLevel', default: '1', type: 'int', min: 0, max: null, risk: 'high', description: 'Nivel de GM que recibe una cuenta marcada como GM sin nivel explícito.' },
      { key: 'GM.LowerSecurity', default: 'false', type: 'bool', min: null, max: null, risk: 'high', description: 'Permite a un GM actuar como si tuviera menor nivel; puede usarse para saltar restricciones.' },
      { key: 'GM.LoginState', default: '2', type: 'int', min: null, max: null, risk: 'medium', description: 'Estado GM al conectar.' },
      { key: 'GM.Visible', default: '2', type: 'int', min: null, max: null, risk: 'low', description: 'Visibilidad del GM.' },
      { key: 'GM.Chat', default: '2', type: 'int', min: null, max: null, risk: 'low', description: 'Color y etiqueta del chat GM.' },
      { key: 'GM.WhisperingTo', default: '2', type: 'int', min: null, max: null, risk: 'low', description: 'Nivel de GM que puede recibir susurros de jugadores.' },
      { key: 'GM.InGMList.Level', default: '3', type: 'int', min: null, max: null, risk: 'high', description: 'Quién aparece en .gmlist.' },
      { key: 'GM.InWhoList.Level', default: '3', type: 'int', min: null, max: null, risk: 'medium', description: 'Quién aparece en la lista de jugadores conectados como GM.' },
      { key: 'GM.AllowInvite', default: 'false', type: 'bool', min: null, max: null, risk: 'low', description: 'Permite a un GM invitar jugadores a grupo estando en modo GM.' },
      { key: 'GM.AllowFriend', default: 'false', type: 'bool', min: null, max: null, risk: 'low', description: 'Permite a un GM añadir amigos estando en modo GM.' },
      { key: 'GM.TicketSystem.ChanceOfGMSurvey', default: '50.0', type: 'float', min: 0, max: 100, risk: 'low', description: 'Probabilidad de mostrar la encuesta de satisfacción tras cerrar un ticket.' },
      // Valores contrastados con worldserver.conf.dist del core fijado.
      { key: 'AllowPlayerCommands', default: '1', type: 'bool', min: null, max: null, risk: 'high', description: 'Permite comandos GM a jugadores según su nivel.' },
      { key: 'StrictNames.Reserved', default: '1', type: 'bool', min: null, max: null, risk: 'high', description: 'Filtro de nombres reservados.' },
      { key: 'StrictNames.Profanity', default: '1', type: 'bool', min: null, max: null, risk: 'high', description: 'Filtro de nombres con groserías.' },
      { key: 'PacketSpoof.BanMode', default: '0', type: 'int', min: null, max: null, risk: 'high', description: 'Control de baneo automático por paquetes de red falsificados.' },
      { key: 'Warden.Enabled', default: '1', type: 'bool', min: null, max: null, risk: 'high', description: 'Anti-cheat del cliente. Desactivarlo debilita la detección de trampas en todo el servidor.' },
      { key: 'Warden.ClientCheckFailAction', default: '0', type: 'int', min: null, max: null, risk: 'high', description: 'Acción del anti-cheat cuando un cliente falla una comprobación.' },
    ],
  },
  {
    id: 'chat-antiflood',
    label: 'Chat y anti-flood',
    group: 'core',
    module: null,
    file: 'worldserver.conf',
    params: [
      { key: 'ChatLevelReq.Channel', default: '1', type: 'int', min: null, max: null, risk: 'low', description: 'Nivel mínimo para usar un canal.' },
      { key: 'ChatLevelReq.Whisper', default: '1', type: 'int', min: null, max: null, risk: 'low', description: 'Nivel mínimo para susurrar.' },
      { key: 'ChatLevelReq.Say', default: '1', type: 'int', min: null, max: null, risk: 'low', description: 'Nivel mínimo para hablar por chat de área.' },
      { key: 'ChatFilter.Whisper', default: 'true', type: 'bool', min: null, max: null, risk: 'low', description: 'Filtra susurros.' },
      { key: 'ChatFilter.Say', default: 'false', type: 'bool', min: null, max: null, risk: 'low', description: 'Filtra chat de área.' },
      { key: 'ChatFilter.Yell', default: 'false', type: 'bool', min: null, max: null, risk: 'low', description: 'Filtra gritos.' },
      { key: 'ChatFilter.Emote', default: 'false', type: 'bool', min: null, max: null, risk: 'low', description: 'Filtra emotes de texto.' },
      { key: 'ChatFlood.MessageCount', default: '10', type: 'int', min: 0, max: null, risk: 'low', description: 'Mensajes antes de considerar flood.' },
      { key: 'ChatFlood.MessageDelay', default: '1', type: 'int', min: 0, max: null, risk: 'low', description: 'Ventana en segundos para contar mensajes de flood.' },
      { key: 'ChatFlood.AddonMessageCount', default: '100', type: 'int', min: 0, max: null, risk: 'low', description: 'Mensajes de addon antes de considerar flood.' },
      { key: 'ChatFlood.AddonMessageDelay', default: '1', type: 'int', min: 0, max: null, risk: 'low', description: 'Ventana en segundos para contar mensajes de addon.' },
      { key: 'ChatFlood.MuteTime', default: '10', type: 'int', min: 0, max: null, risk: 'low', description: 'Silencio automático en segundos tras flood.' },
      { key: 'Chat.MuteFirstLogin', default: 'false', type: 'bool', min: null, max: null, risk: 'low', description: 'Silencia el chat en el primer inicio de sesión de una cuenta.' },
      { key: 'Chat.MuteTimeFirstLogin', default: '120', type: 'int', min: 0, max: null, risk: 'low', description: 'Duración en segundos del silencio en el primer inicio de sesión.' },
      { key: 'ChatFakeMessagePreventing', default: 'true', type: 'bool', min: null, max: null, risk: 'low', description: 'Evita mensajes de chat falsificados.' },
      { key: 'ChatStrictLinkChecking.Severity', default: '0', type: 'int', min: null, max: null, risk: 'low', description: 'Severidad de la comprobación estricta de enlaces de objetos en el chat.' },
      { key: 'ChatStrictLinkChecking.Kick', default: '0', type: 'int', min: null, max: null, risk: 'low', description: 'Expulsa al enviar enlaces de chat inválidos.' },
      { key: 'ChatLog.Enable', default: 'false', type: 'bool', min: null, max: null, risk: 'low', description: 'Activa el registro de chat en base de datos; no altera el juego.' },
    ],
  },
  {
    id: 'announcements',
    label: 'Anuncios automáticos',
    group: 'core',
    module: null,
    file: 'worldserver.conf',
    params: [
      { key: 'AutoBroadcast.On', default: 'false', type: 'bool', min: null, max: null, risk: 'low', description: 'Activa el sistema de mensajes automáticos periódicos.' },
      { key: 'AutoBroadcast.Center', default: '0', type: 'int', min: null, max: null, risk: 'low', description: 'Posición del anuncio (chat o pantalla).' },
      { key: 'AutoBroadcast.Timer', default: '60000', type: 'int', min: 0, max: null, risk: 'low', description: 'Intervalo en milisegundos entre anuncios automáticos.' },
      { key: 'AutoBroadcast.MinDisableLevel', default: '0', type: 'int', min: null, max: null, risk: 'low', description: 'Nivel de GM a partir del cual se puede desactivar la recepción de anuncios.' },
      { key: 'Event.Announce', default: '0', type: 'int', min: null, max: null, risk: 'low', description: 'Anuncio de eventos de juego programados.' },
    ],
  },
  {
    id: 'game-settings',
    label: 'Ajustes de juego',
    group: 'core',
    module: null,
    file: 'worldserver.conf',
    params: [
      { key: 'MaxPlayerLevel', default: '80', type: 'int', min: 1, max: 100, risk: 'high', description: 'Tope de nivel del servidor; cambiarlo mal desincroniza contenido y talentos.' },
      { key: 'StartPlayerLevel', default: '1', type: 'int', min: 1, max: null, risk: 'medium', description: 'Nivel inicial de un personaje nuevo.' },
      { key: 'StartHeroicPlayerLevel', default: '55', type: 'int', min: 1, max: null, risk: 'medium', description: 'Nivel inicial de un personaje heroico nuevo.' },
      { key: 'StartPlayerMoney', default: '0', type: 'int', min: 0, max: null, risk: 'medium', description: 'Impacto económico al crear personaje: oro inicial.' },
      { key: 'StartHeroicPlayerMoney', default: '2000', type: 'int', min: 0, max: null, risk: 'medium', description: 'Oro inicial de un personaje heroico nuevo.' },
      { key: 'StartHonorPoints', default: '0', type: 'int', min: 0, max: null, risk: 'low', description: 'Puntos de honor iniciales de un personaje nuevo.' },
      { key: 'StartArenaPoints', default: '0', type: 'int', min: 0, max: null, risk: 'low', description: 'Puntos de arena iniciales de un personaje nuevo.' },
      { key: 'PlayerStart.CustomSpells', default: 'false', type: 'bool', min: null, max: null, risk: 'medium', description: 'Ya se usó en la fase 3.4 (ver CHANGELOG) para ARAC.' },
      { key: 'PlayerStart.MapsExplored', default: 'false', type: 'bool', min: null, max: null, risk: 'low', description: 'Marca el mapa como explorado desde el inicio.' },
      { key: 'PlayerStart.AllReputation', default: 'false', type: 'bool', min: null, max: null, risk: 'medium', description: 'Otorga reputación exaltada con todas las facciones desde el inicio.' },
      { key: 'AllowTwoSide.Accounts', default: 'true', type: 'bool', min: null, max: null, risk: 'medium', description: 'Permite Alianza y Horda en la misma cuenta.' },
      { key: 'AllowTwoSide.Interaction.Calendar', default: 'false', type: 'bool', min: null, max: null, risk: 'medium', description: 'Relevante en un servidor pequeño con pocos jugadores por facción: interacción de calendario entre facciones.' },
      { key: 'AllowTwoSide.Interaction.Chat', default: 'false', type: 'bool', min: null, max: null, risk: 'medium', description: 'Relevante en un servidor pequeño con pocos jugadores por facción: chat entre facciones.' },
      { key: 'AllowTwoSide.Interaction.Channel', default: 'false', type: 'bool', min: null, max: null, risk: 'medium', description: 'Relevante en un servidor pequeño con pocos jugadores por facción: canales entre facciones.' },
      { key: 'AllowTwoSide.Interaction.Group', default: 'false', type: 'bool', min: null, max: null, risk: 'medium', description: 'Relevante en un servidor pequeño con pocos jugadores por facción: grupos entre facciones.' },
      { key: 'AllowTwoSide.Interaction.Guild', default: 'false', type: 'bool', min: null, max: null, risk: 'medium', description: 'Relevante en un servidor pequeño con pocos jugadores por facción: hermandades entre facciones.' },
      { key: 'AllowTwoSide.Interaction.Arena', default: 'false', type: 'bool', min: null, max: null, risk: 'medium', description: 'Relevante en un servidor pequeño con pocos jugadores por facción: arena entre facciones.' },
      { key: 'AllowTwoSide.Interaction.Auction', default: 'false', type: 'bool', min: null, max: null, risk: 'medium', description: 'Relevante en un servidor pequeño con pocos jugadores por facción: subastas entre facciones.' },
      { key: 'Instance.IgnoreLevel', default: 'false', type: 'bool', min: null, max: null, risk: 'medium', description: 'Permite entrar a mazmorras sin requisito de nivel.' },
      { key: 'Instance.IgnoreRaid', default: 'false', type: 'bool', min: null, max: null, risk: 'medium', description: 'Permite entrar a mazmorras sin requisito de tamaño de grupo.' },
      { key: 'Instance.ResetTimeHour', default: '4', type: 'int', min: 0, max: 23, risk: 'low', description: 'Hora del día en que resetean las instancias.' },
      { key: 'Instance.UnloadDelay', default: '1800000', type: 'int', min: 0, max: null, risk: 'low', description: 'Milisegundos de espera antes de descargar una instancia vacía.' },
      { key: 'DungeonFinder.OptionsMask', default: '5', type: 'int', min: null, max: null, risk: 'medium', description: 'Activa o desactiva partes del buscador de grupo.' },
      { key: 'DungeonFinder.CastDeserter', default: 'true', type: 'bool', min: null, max: null, risk: 'low', description: 'Aplica el efecto de desertor al abandonar el buscador de grupo.' },
      { key: 'DungeonFinder.AllowCompleted', default: 'true', type: 'bool', min: null, max: null, risk: 'low', description: 'Permite repetir mazmorras ya completadas en el buscador de grupo.' },
      { key: 'Wintergrasp.Enable', default: '1', type: 'bool', min: null, max: null, risk: 'medium', description: 'Activa o desactiva el evento de zona completo.' },
      { key: 'Wintergrasp.PlayerMax', default: '120', type: 'int', min: 0, max: null, risk: 'low', description: 'Jugadores máximos por bando en Wintergrasp.' },
      { key: 'Wintergrasp.PlayerMin', default: '0', type: 'int', min: 0, max: null, risk: 'low', description: 'Jugadores mínimos por bando en Wintergrasp.' },
      { key: 'Wintergrasp.PlayerMinLvl', default: '75', type: 'int', min: 0, max: null, risk: 'low', description: 'Nivel mínimo para participar en Wintergrasp.' },
      { key: 'Wintergrasp.BattleTimer', default: '30', type: 'int', min: 0, max: null, risk: 'low', description: 'Minutos que dura la batalla de Wintergrasp.' },
      { key: 'Wintergrasp.NoBattleTimer', default: '150', type: 'int', min: 0, max: null, risk: 'low', description: 'Minutos entre batallas de Wintergrasp.' },
      { key: 'CharDelete.Method', default: '0', type: 'int', min: null, max: null, risk: 'medium', description: 'Borrado inmediato frente a papelera de personajes.' },
      { key: 'CharDelete.KeepDays', default: '30', type: 'int', min: 0, max: null, risk: 'low', description: 'Días que se conserva un personaje borrado en la papelera.' },
      { key: 'ItemDelete.Method', default: '0', type: 'int', min: null, max: null, risk: 'low', description: 'Método de registro al borrar un objeto.' },
      { key: 'ItemDelete.Quality', default: '3', type: 'int', min: null, max: null, risk: 'low', description: 'Calidad mínima de objeto que se registra al borrarse.' },
      { key: 'ItemDelete.ItemLevel', default: '80', type: 'int', min: null, max: null, risk: 'low', description: 'Nivel de objeto mínimo que se registra al borrarse.' },
      { key: 'ItemDelete.KeepDays', default: '0', type: 'int', min: 0, max: null, risk: 'low', description: 'Días que se conserva el registro de un objeto borrado.' },
      { key: 'Guild.CharterCost', default: '1000', type: 'int', min: 0, max: null, risk: 'low', description: 'Coste en cobre de la carta de hermandad.' },
      { key: 'ArenaTeam.CharterCost.2v2', default: '800000', type: 'int', min: 0, max: null, risk: 'low', description: 'Coste en cobre de la carta de equipo de arena 2v2.' },
      { key: 'ArenaTeam.CharterCost.3v3', default: '1200000', type: 'int', min: 0, max: null, risk: 'low', description: 'Coste en cobre de la carta de equipo de arena 3v3.' },
      { key: 'ArenaTeam.CharterCost.5v5', default: '2000000', type: 'int', min: 0, max: null, risk: 'low', description: 'Coste en cobre de la carta de equipo de arena 5v5.' },
      { key: 'Guild.BankTabCost0', default: '1000000', type: 'int', min: 0, max: null, risk: 'low', description: 'Coste en cobre de la 1ª pestaña de banco de hermandad.' },
      { key: 'Guild.BankTabCost1', default: '2500000', type: 'int', min: 0, max: null, risk: 'low', description: 'Coste en cobre de la 2ª pestaña de banco de hermandad.' },
      { key: 'Guild.BankTabCost2', default: '5000000', type: 'int', min: 0, max: null, risk: 'low', description: 'Coste en cobre de la 3ª pestaña de banco de hermandad.' },
      { key: 'Guild.BankTabCost3', default: '10000000', type: 'int', min: 0, max: null, risk: 'low', description: 'Coste en cobre de la 4ª pestaña de banco de hermandad.' },
      { key: 'Guild.BankTabCost4', default: '25000000', type: 'int', min: 0, max: null, risk: 'low', description: 'Coste en cobre de la 5ª pestaña de banco de hermandad.' },
      { key: 'Guild.BankTabCost5', default: '50000000', type: 'int', min: 0, max: null, risk: 'low', description: 'Coste en cobre de la 6ª pestaña de banco de hermandad.' },
      { key: 'Guild.MemberLimit', default: '0', type: 'int', min: 0, max: null, risk: 'low', description: 'Límite de miembros por hermandad; 0 = sin límite.' },
      { key: 'CharactersPerRealm', default: '10', type: 'int', min: 1, max: 10, risk: 'low', description: 'Personajes máximos por reino y cuenta.' },
      { key: 'CharactersPerAccount', default: '50', type: 'int', min: null, max: null, risk: 'low', description: 'Personajes máximos por cuenta en todos los reinos; debe ser >= CharactersPerRealm.' },
      { key: 'HeroicCharactersPerRealm', default: '1', type: 'int', min: 0, max: 10, risk: 'low', description: 'Personajes heroicos máximos por reino.' },
      { key: 'SkipCinematics', default: '0', type: 'int', min: 0, max: 2, risk: 'low', description: 'Omite las cinemáticas de introducción de raza/clase.' },
      { key: 'AllFlightPaths', default: 'false', type: 'bool', min: null, max: null, risk: 'low', description: 'Otorga todas las rutas de vuelo desde el inicio.' },
      { key: 'InstantFlightPaths', default: '0', type: 'int', min: null, max: null, risk: 'low', description: 'Hace instantáneos los vuelos por ruta.' },
      { key: 'MinDualSpecLevel', default: '40', type: 'int', min: 0, max: null, risk: 'low', description: 'Nivel mínimo para desbloquear la doble especialización.' },
      { key: 'Battleground.PrepTime', default: '120', type: 'int', min: 0, max: null, risk: 'low', description: 'Segundos de preparación antes de un campo de batalla.' },
      { key: 'Battleground.QueueAnnouncer.Enable', default: 'false', type: 'bool', min: null, max: null, risk: 'low', description: 'Anuncia por chat quién se pone en cola de campo de batalla.' },
      { key: 'Arena.PrepTime', default: '60', type: 'int', min: 0, max: null, risk: 'low', description: 'Segundos de preparación antes de una arena.' },
      { key: 'Arena.QueueAnnouncer.Enable', default: 'false', type: 'bool', min: null, max: null, risk: 'low', description: 'Anuncia por chat quién se pone en cola de arena.' },
      { key: 'PvPToken.Enable', default: 'false', type: 'bool', min: null, max: null, risk: 'low', description: 'Activa la entrega de un objeto token tras ganar en PvP.' },
      { key: 'PvPToken.ItemID', default: '29434', type: 'int', min: 0, max: null, risk: 'low', description: 'Objeto entregado como token de PvP.' },
      { key: 'PvPToken.ItemCount', default: '1', type: 'int', min: 0, max: null, risk: 'low', description: 'Cantidad de token de PvP entregada.' },
    ],
  },

  // --- Módulos ---

  {
    id: 'module-playerbots',
    label: 'mod-playerbots',
    group: 'module',
    module: 'mod-playerbots',
    file: 'playerbots.conf',
    params: [
      { key: 'AiPlayerbot.Enabled', default: '1', type: 'bool', min: null, max: null, risk: 'high', description: 'Interruptor maestro; afecta a la población de bots de todo el servidor.' },
      { key: 'AiPlayerbot.RandomBotAutologin', default: '1', type: 'bool', min: null, max: null, risk: 'high', description: 'Autologin de bots aleatorios.' },
      { key: 'AiPlayerbot.MinRandomBots', default: '500', type: 'int', min: 0, max: null, risk: 'high', description: 'Cifra alta = carga de CPU/memoria alta; el servidor actual usa un valor propio distinto del .dist, verificar antes de tocar. Con WorldBots.PlayerScale.Enable=1 (mod_world_bots.conf) mod-world-bots lo pisa en caliente cada pocos segundos según jugadores conectados: editar aquí no sirve de nada mientras esté activo.' },
      { key: 'AiPlayerbot.MaxRandomBots', default: '500', type: 'int', min: 0, max: null, risk: 'high', description: 'Cifra alta = carga de CPU/memoria alta; el servidor actual usa un valor propio distinto del .dist, verificar antes de tocar. Con WorldBots.PlayerScale.Enable=1 (mod_world_bots.conf) mod-world-bots lo pisa en caliente cada pocos segundos según jugadores conectados: editar aquí no sirve de nada mientras esté activo.' },
      { key: 'AiPlayerbot.RandomBotMinLevel', default: '1', type: 'int', min: 1, max: null, risk: 'medium', description: 'Nivel mínimo de los bots aleatorios.' },
      { key: 'AiPlayerbot.RandomBotMaxLevel', default: '80', type: 'int', min: 1, max: null, risk: 'medium', description: 'Nivel máximo de los bots aleatorios.' },
      { key: 'AiPlayerbot.MinRandomBotInWorldTime', default: '600', type: 'int', min: 0, max: null, risk: 'low', description: 'Segundos mínimos que un bot aleatorio permanece en el mundo.' },
      { key: 'AiPlayerbot.MaxRandomBotInWorldTime', default: '28800', type: 'int', min: 0, max: null, risk: 'low', description: 'Segundos máximos que un bot aleatorio permanece en el mundo.' },
    ],
  },
  {
    id: 'module-autobalance',
    label: 'mod-autobalance',
    group: 'module',
    module: 'mod-autobalance',
    file: 'AutoBalance.conf',
    params: [
      { key: 'AutoBalance.Enable.Global', default: '1', type: 'bool', min: null, max: null, risk: 'high', description: 'Interruptor maestro de todo el módulo.' },
      { key: 'AutoBalance.Enable.5M', default: '1', type: 'bool', min: null, max: null, risk: 'medium', description: 'Activa o desactiva el balanceo en mazmorras de 5 jugadores.' },
      { key: 'AutoBalance.Enable.10M', default: '1', type: 'bool', min: null, max: null, risk: 'medium', description: 'Activa o desactiva el balanceo en bandas de 10 jugadores.' },
      { key: 'AutoBalance.Enable.15M', default: '1', type: 'bool', min: null, max: null, risk: 'medium', description: 'Activa o desactiva el balanceo en bandas de 15 jugadores.' },
      { key: 'AutoBalance.Enable.20M', default: '1', type: 'bool', min: null, max: null, risk: 'medium', description: 'Activa o desactiva el balanceo en bandas de 20 jugadores.' },
      { key: 'AutoBalance.Enable.25M', default: '1', type: 'bool', min: null, max: null, risk: 'medium', description: 'Activa o desactiva el balanceo en bandas de 25 jugadores.' },
      { key: 'AutoBalance.Enable.40M', default: '1', type: 'bool', min: null, max: null, risk: 'medium', description: 'Activa o desactiva el balanceo en bandas de 40 jugadores.' },
      { key: 'AutoBalance.Enable.OtherNormal', default: '1', type: 'bool', min: null, max: null, risk: 'medium', description: 'Activa o desactiva el balanceo en otras instancias normales.' },
      { key: 'AutoBalance.Enable.5MHeroic', default: '1', type: 'bool', min: null, max: null, risk: 'medium', description: 'Activa o desactiva el balanceo en mazmorras heroicas de 5.' },
      { key: 'AutoBalance.Enable.10MHeroic', default: '1', type: 'bool', min: null, max: null, risk: 'medium', description: 'Activa o desactiva el balanceo en bandas heroicas de 10.' },
      { key: 'AutoBalance.Enable.25MHeroic', default: '1', type: 'bool', min: null, max: null, risk: 'medium', description: 'Activa o desactiva el balanceo en bandas heroicas de 25.' },
      { key: 'AutoBalance.Enable.OtherHeroic', default: '1', type: 'bool', min: null, max: null, risk: 'medium', description: 'Activa o desactiva el balanceo en otras instancias heroicas.' },
      { key: 'AutoBalance.MinPlayers', default: '1', type: 'int', min: 0, max: null, risk: 'medium', description: 'Jugadores mínimos para que se aplique el balanceo.' },
      { key: 'AutoBalance.MinPlayers.Heroic', default: '1', type: 'int', min: 0, max: null, risk: 'medium', description: 'Jugadores mínimos para balanceo en heroica.' },
      { key: 'AutoBalance.MinPlayers.Raid', default: '1', type: 'int', min: 0, max: null, risk: 'medium', description: 'Jugadores mínimos para balanceo en banda.' },
      { key: 'AutoBalance.MinPlayers.RaidHeroic', default: '1', type: 'int', min: 0, max: null, risk: 'medium', description: 'Jugadores mínimos para balanceo en banda heroica.' },
      { key: 'AutoBalance.playerCountDifficultyOffset', default: '0', type: 'int', min: null, max: null, risk: 'medium', description: 'Desplaza la dificultad calculada.' },
    ],
  },
  {
    id: 'module-ah-bot-plus',
    label: 'mod-ah-bot-plus',
    group: 'module',
    module: 'mod-ah-bot-plus',
    file: 'mod_ahbot.conf',
    params: [
      { key: 'AuctionHouseBot.EnableSeller', default: 'false', type: 'bool', min: null, max: null, risk: 'medium', description: 'Activa bots vendedores en la casa de subastas.' },
      { key: 'AuctionHouseBot.Buyer.Enabled', default: 'false', type: 'bool', min: null, max: null, risk: 'medium', description: 'Activa bots compradores en la casa de subastas.' },
      { key: 'AuctionHouseBot.MinutesBetweenBuyCycle', default: '1', type: 'int', min: 0, max: null, risk: 'low', description: 'Minutos entre ciclos de compra de los bots.' },
      { key: 'AuctionHouseBot.Buyer.BidAgainstPlayers', default: 'false', type: 'bool', min: null, max: null, risk: 'medium', description: 'Si un bot puede pujar contra jugadores reales.' },
    ],
  },
  {
    id: 'module-dungeon-master',
    label: 'mod-dungeon-master',
    group: 'module',
    module: 'mod-dungeon-master',
    file: 'mod_dungeon_master.conf',
    params: [
      { key: 'DungeonMaster.Enable', default: '1', type: 'bool', min: null, max: null, risk: 'medium', description: 'Interruptor maestro del módulo.' },
      { key: 'DungeonMaster.Rewards.BaseGold', default: '50000', type: 'int', min: 0, max: null, risk: 'medium', description: 'Impacto económico: oro base de recompensa en cobre.' },
      { key: 'DungeonMaster.Rewards.GoldPerMob', default: '50', type: 'int', min: 0, max: null, risk: 'medium', description: 'Impacto económico: oro por criatura derrotada en cobre.' },
      { key: 'DungeonMaster.Rewards.GoldPerBoss', default: '10000', type: 'int', min: 0, max: null, risk: 'medium', description: 'Impacto económico: oro por jefe derrotado en cobre.' },
      { key: 'DungeonMaster.Rewards.XPMultiplier', default: '1.0', type: 'float', min: 0, max: null, risk: 'low', description: 'Multiplicador de experiencia de las recompensas.' },
      { key: 'DungeonMaster.Rewards.ItemChance', default: '80', type: 'int', min: 0, max: 100, risk: 'low', description: 'Probabilidad de recompensa de objeto.' },
      { key: 'DungeonMaster.Rewards.RareChance', default: '40', type: 'int', min: 0, max: 100, risk: 'low', description: 'Probabilidad de que el objeto de recompensa sea raro.' },
      { key: 'DungeonMaster.Rewards.EpicChance', default: '15', type: 'int', min: 0, max: 100, risk: 'low', description: 'Probabilidad de que el objeto de recompensa sea épico.' },
      { key: 'DungeonMaster.MaxConcurrentRuns', default: '20', type: 'int', min: 0, max: null, risk: 'low', description: 'Ejecuciones simultáneas máximas.' },
      { key: 'DungeonMaster.Cooldown.Minutes', default: '5', type: 'int', min: 0, max: null, risk: 'low', description: 'Minutos de espera entre ejecuciones.' },
      { key: 'DungeonMaster.TimeLimit.Enable', default: '0', type: 'bool', min: null, max: null, risk: 'low', description: 'Activa el límite de tiempo por ejecución.' },
      { key: 'DungeonMaster.TimeLimit.Minutes', default: '30', type: 'int', min: 0, max: null, risk: 'low', description: 'Minutos del límite de tiempo por ejecución.' },
      { key: 'DungeonMaster.Roguelike.Enable', default: '1', type: 'bool', min: null, max: null, risk: 'medium', description: 'Activa el modo de dificultad progresiva completo.' },
    ],
  },
  {
    id: 'module-dungeon-clear',
    label: 'mod-dungeon-clear',
    group: 'module',
    module: 'mod-dungeon-clear',
    file: 'mod_dungeon_clear.conf',
    params: [
      { key: 'DungeonClear.Enable', default: '1', type: 'bool', min: null, max: null, risk: 'medium', description: 'Interruptor maestro; el propio .conf.dist confirma que se honra en .reload config, aunque en este panel siempre se trata como reinicio.' },
      { key: 'DungeonClear.LootMinQuality', default: '0', type: 'int', min: 0, max: 4, risk: 'low', description: 'Calidad mínima de objeto que suelta la limpieza automática.' },
      { key: 'DungeonClear.RestHealthPct', default: '0', type: 'int', min: 0, max: 100, risk: 'low', description: 'Porcentaje de vida restaurado tras la limpieza.' },
      { key: 'DungeonClear.RestManaPct', default: '0', type: 'int', min: 0, max: 100, risk: 'low', description: 'Porcentaje de maná restaurado tras la limpieza.' },
      { key: 'DungeonClear.SmartRest', default: '0', type: 'bool', min: null, max: null, risk: 'low', description: 'Ajusta el descanso automáticamente según el contexto.' },
    ],
  },
  {
    id: 'module-transmog',
    label: 'mod-transmog',
    group: 'module',
    module: 'mod-transmog',
    file: 'transmog.conf',
    params: [
      { key: 'Transmogrification.Enable', default: '1', type: 'bool', min: null, max: null, risk: 'medium', description: 'Interruptor maestro del transmog.' },
      { key: 'Transmogrification.UseCollectionSystem', default: '1', type: 'bool', min: null, max: null, risk: 'low', description: 'Usa el sistema de colección de apariencias.' },
      { key: 'Transmogrification.ScaledCostModifier', default: '1.0', type: 'float', min: 0, max: null, risk: 'medium', description: 'Coste económico del transmog.' },
      { key: 'Transmogrification.CopperCost', default: '0', type: 'int', min: 0, max: null, risk: 'medium', description: 'Coste fijo en cobre por transmog.' },
      { key: 'Transmogrification.RequireToken', default: '0', type: 'bool', min: null, max: null, risk: 'low', description: 'Exige un objeto token para transmogrificar.' },
      { key: 'Transmogrification.TokenEntry', default: '49426', type: 'int', min: 0, max: null, risk: 'low', description: 'Objeto usado como token de transmog.' },
      { key: 'Transmogrification.TokenAmount', default: '1', type: 'int', min: 0, max: null, risk: 'low', description: 'Cantidad de token exigida por transmog.' },
      // Valores contrastados con transmog.conf.dist del módulo fijado.
      { key: 'Transmogrification.AllowPoor', default: '0', type: 'bool', min: null, max: null, risk: 'low', description: 'Permite usar objetos de calidad Pobre como origen del transmog.' },
      { key: 'Transmogrification.AllowCommon', default: '0', type: 'bool', min: null, max: null, risk: 'low', description: 'Permite usar objetos de calidad Normal como origen del transmog.' },
      { key: 'Transmogrification.AllowUncommon', default: '1', type: 'bool', min: null, max: null, risk: 'low', description: 'Permite usar objetos de calidad Excepcional como origen del transmog.' },
      { key: 'Transmogrification.AllowRare', default: '1', type: 'bool', min: null, max: null, risk: 'low', description: 'Permite usar objetos de calidad Rara como origen del transmog.' },
      { key: 'Transmogrification.AllowEpic', default: '1', type: 'bool', min: null, max: null, risk: 'low', description: 'Permite usar objetos de calidad Épica como origen del transmog.' },
      { key: 'Transmogrification.AllowLegendary', default: '0', type: 'bool', min: null, max: null, risk: 'low', description: 'Permite usar objetos de calidad Legendaria como origen del transmog.' },
      { key: 'Transmogrification.AllowArtifact', default: '0', type: 'bool', min: null, max: null, risk: 'low', description: 'Permite usar objetos de calidad Artefacto como origen del transmog.' },
      { key: 'Transmogrification.AllowHeirloom', default: '1', type: 'bool', min: null, max: null, risk: 'low', description: 'Permite usar objetos de calidad Herencia como origen del transmog.' },
    ],
  },
  {
    id: 'module-individual-progression',
    label: 'mod-individual-progression',
    group: 'module',
    module: 'mod-individual-progression',
    file: 'individualProgression.conf',
    params: [
      { key: 'IndividualProgression.Enable', default: '1', type: 'bool', min: null, max: null, risk: 'high', description: 'Interruptor maestro de todo el sistema de progresión por fases.' },
      { key: 'IndividualProgression.ProgressionLimit', default: '0', type: 'int', min: 0, max: 18, risk: 'high', description: 'Topa artificialmente el contenido accesible.' },
      { key: 'IndividualProgression.StartingProgression', default: '0', type: 'int', min: 0, max: 18, risk: 'high', description: 'Fase de progresión con la que empiezan los personajes nuevos.' },
      { key: 'IndividualProgression.DisableRDF', default: '0', type: 'bool', min: null, max: null, risk: 'medium', description: 'Desactiva el buscador de grupo aleatorio.' },
      { key: 'IndividualProgression.BotAccountsMaxLevel', default: '80', type: 'int', min: 1, max: null, risk: 'medium', description: 'Nivel máximo permitido para cuentas de bots.' },
    ],
  },
  {
    id: 'module-progression-skip',
    label: 'mod-progression-skip (Cronista de las Eras)',
    group: 'module',
    module: 'mod-progression-skip',
    file: 'mod_progression_skip.conf',
    params: [
      { key: 'ProgressionSkip.Enable', default: '0', type: 'bool', min: null, max: null, risk: 'high', description: 'Interruptor general del NPC "Cronista de las Eras". Con 0 sigue en el mundo pero no ofrece ningún salto de fase.' },
      { key: 'ProgressionSkip.RequireNoGroup', default: '1', type: 'bool', min: null, max: null, risk: 'medium', description: 'Exige salir del grupo para confirmar un salto. Con 0 se permite confirmar estando en grupo.' },
    ],
  },
  {
    id: 'module-challenge-modes',
    label: 'mod-challenge-modes',
    group: 'module',
    module: 'mod-challenge-modes',
    file: 'challenge_modes.conf',
    params: [
      { key: 'ChallengeModes.Enable', default: '1', type: 'bool', min: null, max: null, risk: 'medium', description: 'Interruptor maestro del módulo.' },
      { key: 'Hardcore.Enable', default: '1', type: 'bool', min: null, max: null, risk: 'medium', description: 'Modo de reto Hardcore.' },
      { key: 'SemiHardcore.Enable', default: '1', type: 'bool', min: null, max: null, risk: 'medium', description: 'Modo de reto Semi-Hardcore.' },
      { key: 'SelfCrafted.Enable', default: '1', type: 'bool', min: null, max: null, risk: 'medium', description: 'Modo de reto Autocraft.' },
      { key: 'ItemQualityLevel.Enable', default: '1', type: 'bool', min: null, max: null, risk: 'medium', description: 'Modo de reto de calidad de objeto limitada.' },
      { key: 'SlowXpGain.Enable', default: '1', type: 'bool', min: null, max: null, risk: 'medium', description: 'Modo de reto de experiencia lenta.' },
      { key: 'VerySlowXpGain.Enable', default: '1', type: 'bool', min: null, max: null, risk: 'medium', description: 'Modo de reto de experiencia muy lenta.' },
      { key: 'QuestXpOnly.Enable', default: '1', type: 'bool', min: null, max: null, risk: 'medium', description: 'Modo de reto de experiencia sólo por misiones.' },
      { key: 'IronMan.Enable', default: '1', type: 'bool', min: null, max: null, risk: 'medium', description: 'Modo de reto Iron Man.' },
      { key: 'SlowXpGain.XPMultiplier', default: '0.50', type: 'float', min: 0, max: null, risk: 'low', description: 'Multiplicador de experiencia del modo de experiencia lenta.' },
      { key: 'VerySlowXpGain.XPMultiplier', default: '0.25', type: 'float', min: 0, max: null, risk: 'low', description: 'Multiplicador de experiencia del modo de experiencia muy lenta.' },
    ],
  },
  {
    id: 'module-instanced-worldbosses',
    label: 'mod-instanced-worldbosses',
    group: 'module',
    module: 'mod-instanced-worldbosses',
    file: 'mod-instanced-worldbosses.conf',
    params: [
      { key: 'ModInstancedWorldBosses.Enable', default: '0', type: 'bool', min: null, max: null, risk: 'medium', description: 'Interruptor maestro del módulo.' },
      { key: 'ModInstancedWorldBosses.ResetTimerSecs', default: '25920', type: 'int', min: 0, max: null, risk: 'low', description: 'Segundos hasta el reseteo del jefe (3 días por defecto).' },
      { key: 'ModInstancedWorldBosses.RespawnTimerSecs', default: '3600', type: 'int', min: 0, max: null, risk: 'low', description: 'Segundos hasta el reaparición del jefe.' },
      { key: 'ModInstancedWorldBosses.GracePeriodSecs', default: '300', type: 'int', min: 0, max: null, risk: 'low', description: 'Segundos de periodo de gracia antes del combate.' },
    ],
  },
  {
    id: 'module-instance-reset',
    label: 'mod-instance-reset',
    group: 'module',
    module: 'mod-instance-reset',
    file: 'instance-reset.conf',
    params: [
      { key: 'instanceReset.Enable', default: 'true', type: 'bool', min: null, max: null, risk: 'medium', description: 'Interruptor maestro del módulo.' },
      { key: 'instanceReset.NormalModeOnly', default: 'false', type: 'bool', min: null, max: null, risk: 'low', description: 'Limita el reseteo manual a dificultad normal.' },
      { key: 'instanceReset.TransactionType', default: '0', type: 'int', min: null, max: null, risk: 'medium', description: 'Determina si cobra dinero o token por el reseteo.' },
      { key: 'instanceReset.TokenID', default: '49426', type: 'int', min: 0, max: null, risk: 'medium', description: 'Precio del reseteo manual de mazmorra: objeto token.' },
      { key: 'instanceReset.TokenCount', default: '26', type: 'int', min: 0, max: null, risk: 'medium', description: 'Precio del reseteo manual de mazmorra: cantidad de token.' },
      { key: 'instanceReset.MoneyCount', default: '10000000', type: 'int', min: 0, max: null, risk: 'medium', description: 'Precio del reseteo manual de mazmorra: cobre.' },
    ],
  },
  {
    id: 'module-1v1-arena',
    label: 'mod-1v1-arena',
    group: 'module',
    module: 'mod-1v1-arena',
    file: '1v1arena.conf',
    params: [
      { key: 'Arena1v1.Enable', default: '1', type: 'bool', min: null, max: null, risk: 'medium', description: 'Interruptor maestro del módulo.' },
      { key: 'Arena1v1.MinLevel', default: '80', type: 'int', min: 1, max: null, risk: 'low', description: 'Nivel mínimo para entrar en arena 1v1.' },
      { key: 'Arena1v1.Costs', default: '400000', type: 'int', min: 0, max: null, risk: 'low', description: 'Coste en cobre de entrar en arena 1v1.' },
      { key: 'Arena1v1.ArenaPointsMulti', default: '0.64', type: 'float', min: 0, max: null, risk: 'low', description: 'Multiplicador de puntos de arena obtenidos en 1v1.' },
      { key: 'Arena1v1.PreventHealingTalents', default: 'false', type: 'bool', min: null, max: null, risk: 'low', description: 'Impide talentos de sanación en arena 1v1.' },
      { key: 'Arena1v1.PreventTankTalents', default: 'false', type: 'bool', min: null, max: null, risk: 'low', description: 'Impide talentos de tanque en arena 1v1.' },
    ],
  },
  {
    id: 'module-random-enchants',
    label: 'mod-random-enchants',
    group: 'module',
    module: 'mod-random-enchants',
    file: 'random_enchants.conf',
    params: [
      { key: 'RandomEnchants.Enable', default: '1', type: 'bool', min: null, max: null, risk: 'medium', description: 'Interruptor maestro del módulo.' },
      { key: 'RandomEnchants.OnLoot', default: '1', type: 'bool', min: null, max: null, risk: 'low', description: 'Aplica encantado aleatorio al saquear un objeto.' },
      { key: 'RandomEnchants.OnCreate', default: '1', type: 'bool', min: null, max: null, risk: 'low', description: 'Aplica encantado aleatorio al crear un objeto.' },
      { key: 'RandomEnchants.OnQuestReward', default: '1', type: 'bool', min: null, max: null, risk: 'low', description: 'Aplica encantado aleatorio a recompensas de misión.' },
      { key: 'RandomEnchants.OnGroupRoll', default: '1', type: 'bool', min: null, max: null, risk: 'low', description: 'Aplica encantado aleatorio a tiradas de grupo.' },
      { key: 'RandomEnchants.EnchantChance1', default: '70.0', type: 'float', min: 0, max: 100, risk: 'low', description: 'Probabilidad de encantado en cascada, primer nivel.' },
      { key: 'RandomEnchants.EnchantChance2', default: '65.0', type: 'float', min: 0, max: 100, risk: 'low', description: 'Probabilidad de encantado en cascada, segundo nivel.' },
      { key: 'RandomEnchants.EnchantChance3', default: '60.0', type: 'float', min: 0, max: 100, risk: 'low', description: 'Probabilidad de encantado en cascada, tercer nivel.' },
    ],
  },
  {
    id: 'module-token-turnin',
    label: 'mod-token-turnin',
    group: 'module',
    module: 'mod-token-turnin',
    file: 'mod_token_turnin.conf',
    params: [
      { key: 'TokenTurnIn.Enable', default: '1', type: 'bool', min: null, max: null, risk: 'low', description: 'Interruptor maestro del módulo.' },
      { key: 'TokenTurnIn.IncludeSelf', default: '0', type: 'bool', min: null, max: null, risk: 'low', description: 'Incluye a la propia cuenta en la entrega de tokens.' },
      { key: 'TokenTurnIn.IncludeRealPlayers', default: '0', type: 'bool', min: null, max: null, risk: 'low', description: 'Incluye a jugadores reales en la entrega de tokens.' },
    ],
  },
  {
    id: 'module-world-buff-bots',
    label: 'mod-world-buff-bots',
    group: 'module',
    module: 'mod-world-buff-bots',
    file: 'mod_world_buff_bots.conf',
    params: [
      { key: 'WorldBuffBots.Enable', default: '1', type: 'bool', min: null, max: null, risk: 'low', description: 'Interruptor maestro del módulo.' },
      { key: 'WorldBuffBots.BaseMinutes', default: '90', type: 'int', min: 0, max: null, risk: 'low', description: 'Minutos base entre buffs de mundo simulados.' },
      { key: 'WorldBuffBots.VarianceMinutes', default: '60', type: 'int', min: 0, max: null, risk: 'low', description: 'Variación en minutos sobre el intervalo base.' },
      { key: 'WorldBuffBots.Warchief.Enable', default: '1', type: 'bool', min: null, max: null, risk: 'low', description: 'Activa el buff de mundo del Jefe de Guerra.' },
      { key: 'WorldBuffBots.Dragonslayer.Enable', default: '1', type: 'bool', min: null, max: null, risk: 'low', description: 'Activa el buff de mundo de Matadragón.' },
      { key: 'WorldBuffBots.Zandalar.Enable', default: '1', type: 'bool', min: null, max: null, risk: 'low', description: 'Activa el buff de mundo de Zandalar.' },
    ],
  },
  {
    id: 'module-war-effort',
    label: 'mod-war-effort',
    group: 'module',
    module: 'mod-war-effort',
    file: 'mod_aq_war_effort.conf',
    params: [
      { key: 'ModWarEffort.Enable', default: '0', type: 'bool', min: null, max: null, risk: 'low', description: 'Interruptor maestro del módulo.' },
      { key: 'ModWarEffort.Id', default: '1', type: 'int', min: null, max: null, risk: 'low', description: 'Cambiarlo reinicia la campaña.' },
      // Las 50 claves de objetivos por etapa (ModWarEffort.Goal.*) quedan fuera:
      // el propio documento origen recomienda un editor de tabla dedicado en vez
      // de 50 campos sueltos.
    ],
  },
  {
    id: 'module-reagent-bank',
    label: 'mod-reagent-bank',
    group: 'module',
    module: 'mod-reagent-bank',
    file: 'reagent_bank.conf',
    params: [
      { key: 'ReagentBank.Enable', default: '1', type: 'bool', min: null, max: null, risk: 'low', description: 'Única clave del módulo.' },
    ],
  },
  {
    id: 'module-racial-trait-swap',
    label: 'mod-racial-trait-swap',
    group: 'module',
    module: 'mod-racial-trait-swap',
    file: 'RacialTraitSwap.conf',
    params: [
      { key: 'Racial.Traits.Swap.Gold', default: '10', type: 'int', min: 0, max: null, risk: 'low', description: 'Coste en oro del intercambio de rasgo racial.' },
    ],
  },
  {
    id: 'module-congrats-on-level',
    label: 'mod-congrats-on-level',
    group: 'module',
    module: 'mod-congrats-on-level',
    file: 'mod_congratsonlevel.conf',
    params: [
      { key: 'Congrats.Enable', default: '1', type: 'bool', min: null, max: null, risk: 'low', description: 'Interruptor maestro del módulo.' },
      { key: 'CongratsPerLevel.Enable', default: '1', type: 'bool', min: null, max: null, risk: 'low', description: 'Felicitación en cada nivel, no sólo en hitos.' },
    ],
  },
  {
    id: 'module-home-guild',
    label: 'mod-home-guild',
    group: 'module',
    module: 'mod-home-guild',
    file: 'mod_home_guild.conf',
    params: [
      { key: 'HomeGuild.Enable', default: '1', type: 'bool', min: null, max: null, risk: 'medium', description: 'Interruptor maestro de la hermandad automática.' },
      { key: 'HomeGuild.Members', default: '15', type: 'int', min: 0, max: null, risk: 'low', description: 'Tamaño de grupo objetivo.' },
      { key: 'HomeGuild.AutoAdopt', default: '1', type: 'bool', min: null, max: null, risk: 'low', description: 'Fundar una hermandad la convierte en hermandad de casa automáticamente. Con 0, se activa a mano con ".hermandad activar".' },
      { key: 'HomeGuild.InactiveOwnerReclaimDays', default: '30', type: 'int', min: 0, max: null, risk: 'medium', description: 'Días sin entrar el fundador (y sin estar conectado) antes de expulsar a sus bots de la hermandad y devolverlos al pool. Con 0 no se reclama nunca.' },
      { key: 'HomeGuild.MaxOnlineBots', default: '0', type: 'int', min: 0, max: null, risk: 'medium', description: 'Tope propio de bots de hermandad conectados a la vez. 0 usa AiPlayerbot.MaxRandomBots; nunca lo supera.' },
      { key: 'HomeGuild.CareIntervalSeconds', default: '30', type: 'int', min: 1, max: null, risk: 'low', description: 'Cada cuántos segundos se cuida cada hermandad (recluta, conecta, re-nivela).' },
      { key: 'HomeGuild.KeepOnlineBatch', default: '5', type: 'int', min: 1, max: null, risk: 'low', description: 'Bots de la hermandad que se conectan por pasada.' },
      { key: 'HomeGuild.ReLevelPerPass', default: '1', type: 'int', min: 1, max: null, risk: 'low', description: 'Bots de la hermandad que se suben de nivel por pasada (es caro).' },
      { key: 'HomeGuild.RecruitFromOfflinePool', default: '1', type: 'bool', min: null, max: null, risk: 'low', description: 'Reclutar también de la tabla de personajes (bots desconectados), no solo de los ya conectados y libres.' },
      { key: 'HomeGuild.AnnounceWhenGuildless', default: '1', type: 'bool', min: null, max: null, risk: 'low', description: 'Aviso "monta una hermandad" al entrar sin hermandad (además de Announce).' },
      { key: 'HomeGuild.Tanks', default: '0', type: 'int', min: 0, max: null, risk: 'low', description: 'Tanques objetivo en el roster: al reclutar, los candidatos conectados que llenan el hueco de rol se prueban primero. 0 = por tamaño.' },
      { key: 'HomeGuild.Healers', default: '0', type: 'int', min: 0, max: null, risk: 'low', description: 'Sanadores objetivo en el roster. 0 = por tamaño.' },
      { key: 'HomeGuild.GearMode', default: '1', type: 'int', min: 0, max: 2, risk: 'low', description: 'Mantener el equipo de los bots de casa conectados a la fase del owner aunque no estén en su grupo. 0 = no tocar, 1 = media + margen sin pasar del tope de fase, 2 = solo el tope de fase.' },
    ],
  },
  {
    id: 'module-party-here',
    label: 'mod-party-here',
    group: 'module',
    module: 'mod-party-here',
    file: 'mod_party_here.conf',
    params: [
      { key: 'PartyHere.Enable', default: '1', type: 'bool', min: null, max: null, risk: 'medium', description: 'Interruptor maestro del módulo.' },
      { key: 'PartyHere.MaxRaidBots', default: '39', type: 'int', min: 0, max: null, risk: 'medium', description: 'Ligado a AiPlayerbot.MaxAddedBots; no debería superarlo.' },
      { key: 'PartyHere.LoadGraceSeconds', default: '30', type: 'int', min: 0, max: null, risk: 'low', description: 'Margen mientras el líder cambia de mapa (mazmorra, piedra de hogar, vuelo entre continentes): durante ese rato la party no se deshace. Al desconectarse del todo se disuelve al momento.' },
      { key: 'PartyHere.BotMinWorldSeconds', default: '60', type: 'int', min: 0, max: null, risk: 'low', description: 'Espera tras conectar un bot antes de teletransportarlo junto al líder; protege el asentamiento de su sesión.' },
      { key: 'PartyHere.DismissAutoOnZoneChange', default: '0', type: 'bool', min: null, max: null, risk: 'low', description: 'Echar a los compañeros automáticos al cambiar de zona aunque la misión de grupo que los trajo siga activa. Por defecto 0: muchas misiones "(Grupo)" se aceptan en un sitio y se hacen o entregan en otro.' },
      { key: 'PartyHere.MaxGroupBots', default: '0', type: 'int', min: 0, max: 40, risk: 'low', description: 'Tope de bots para ".grupo N" (no ".grupo banda"). 0 usa PartyHere.MaxRaidBots.' },
      { key: 'PartyHere.Tanks', default: '0', type: 'int', min: 0, max: 40, risk: 'low', description: 'Tanques fijos en el grupo antes de meter DPS. 0 = según el tamaño.' },
      { key: 'PartyHere.Healers', default: '0', type: 'int', min: 0, max: 40, risk: 'low', description: 'Sanadores fijos en el grupo antes de meter DPS. 0 = según el tamaño.' },
      { key: 'PartyHere.AutoQuestMinSuggested', default: '0', type: 'int', min: 0, max: null, risk: 'low', description: 'Umbral mínimo de "jugadores sugeridos" de una misión para invitar bots en automático. 0 = cualquiera que sugiera al menos 1.' },
      { key: 'PartyHere.ResurrectOnSummon', default: '1', type: 'bool', min: null, max: null, risk: 'low', description: 'Revivir al bot muerto antes de traerlo junto al líder.' },
      { key: 'PartyHere.Replenish', default: '1', type: 'bool', min: null, max: null, risk: 'low', description: 'Reponer compañeros que se van de un grupo manual (".grupo N" / ".grupo banda"): si el grupo baja de su tamaño y no estás en instancia, se buscan bots hasta volver a llenarlo. Los grupos automáticos por misión no se reponen.' },
      { key: 'PartyHere.PersistMinutes', default: '10', type: 'int', min: 0, max: null, risk: 'low', description: 'Si te desconectas con un grupo manual de más de 5 y vuelves antes de estos minutos, se te recompone un grupo del mismo tamaño al entrar. 0 lo desactiva.' },
      { key: 'PartyHere.PendingTimeoutSeconds', default: '180', type: 'int', min: 10, max: null, risk: 'low', description: 'Si al pedir compañeros no hay bots suficientes, la petición queda pendiente y se completa sola cuando despiertan; pasados estos segundos se abandona con aviso.' },
      { key: 'PartyHere.PendingRetrySeconds', default: '5', type: 'int', min: 1, max: null, risk: 'low', description: 'Segundos entre intentos de completar una petición de compañeros pendiente.' },
      { key: 'PartyHere.PendingWakeSeconds', default: '45', type: 'int', min: 5, max: null, risk: 'low', description: 'Mínimo de segundos entre tandas de despertar bots para la misma petición pendiente.' },
      { key: 'PartyHere.RoleWaitSeconds', default: '45', type: 'int', min: 0, max: null, risk: 'low', description: 'Grupo manual: segundos que se guardan las plazas de tanque y sanador esperando a un bot de ese rol antes de cubrirlas con cualquiera. 0 = cubrir al momento.' },
      { key: 'PartyHere.RoleRespec', default: '0', type: 'bool', min: null, max: null, risk: 'medium', description: 'Grupo manual: pasada la espera de rol sin tanque o sin sanador, un bot libre de una clase capaz cambia su rama de talentos a la del rol que falta (se queda así). Si no hay ninguno, se avisa al jugador.' },
      { key: 'PartyHere.DismissExcludeMinutes', default: '10', type: 'int', min: 0, max: null, risk: 'low', description: 'Minutos durante los que un bot echado (".grupo fuera <nombre>") o cambiado (".grupo cambia") no vuelve a tu grupo. 0 = sin exclusión.' },
      { key: 'PartyHere.AnnounceErrors', default: '1', type: 'bool', min: null, max: null, risk: 'low', description: 'Mostrar los mensajes de fallo del módulo, aparte del interruptor Announce.' },
      { key: 'PartyHere.ScanIntervalMs', default: '3000', type: 'int', min: 500, max: null, risk: 'low', description: 'Milisegundos entre pasadas del recorrido de parties (traer bots, echar automáticos, limpiar).' },
      { key: 'PartyHere.SummonGiveUpSeconds', default: '60', type: 'int', min: 5, max: null, risk: 'low', description: 'Cuánto se sigue intentando traer a un bot que no vino antes de dejarlo donde esté.' },
      { key: 'PartyHere.SummonDistance', default: '40', type: 'int', min: 5, max: null, risk: 'low', description: 'A partir de cuántas yardas se considera que el bot "ya está cerca" y no se le trae.' },
      { key: 'PartyHere.WakeThrottleSeconds', default: '15', type: 'int', min: 1, max: null, risk: 'low', description: 'Margen entre tandas de despertar bots dormidos.' },
    ],
  },
  {
    id: 'module-quest-mates',
    label: 'mod-quest-mates',
    group: 'module',
    module: 'mod-quest-mates',
    file: 'mod_quest_mates.conf',
    params: [
      { key: 'QuestMates.Enable', default: '1', type: 'bool', min: null, max: null, risk: 'medium', description: 'Interruptor maestro del módulo.' },
      { key: 'QuestMates.MinMates', default: '2', type: 'int', min: 0, max: null, risk: 'low', description: 'Número mínimo de compañeros de misión.' },
      { key: 'QuestMates.MaxMates', default: '3', type: 'int', min: 0, max: null, risk: 'low', description: 'Número máximo de compañeros de misión.' },
      { key: 'QuestMates.RpgStrategyPush', default: '1', type: 'bool', min: null, max: null, risk: 'low', description: 'Al darle la misión al bot, forzarle la estrategia "new rpg" de playerbots para que vaya a por los objetivos en vez de seguir viajando.' },
      { key: 'QuestMates.FollowAbandon', default: '1', type: 'bool', min: null, max: null, risk: 'low', description: 'Si el jugador abandona una misión, sus compañeros sueltan también la copia que les inyectó el módulo (y la quitan de su diario).' },
      { key: 'QuestMates.PreferHomeGuild', default: '1', type: 'bool', min: null, max: null, risk: 'low', description: 'Al elegir compañeros nuevos, los bots de tu hermandad de casa (mod-home-guild) van primero.' },
      { key: 'QuestMates.JointTurnIn', default: '1', type: 'bool', min: null, max: null, risk: 'low', description: 'Cuando el jugador entrega una misión y un compañero la tiene completa, reenfocar su IA para que vaya a entregarla al PNJ.' },
      { key: 'QuestMates.MaxMatesTracked', default: '6', type: 'int', min: 1, max: null, risk: 'low', description: 'Tope de bots que un jugador retiene como compañeros de misión a la vez.' },
      { key: 'QuestMates.CleanupIntervalMs', default: '3000', type: 'int', min: 500, max: null, risk: 'low', description: 'Milisegundos entre barridos de limpieza de reservas de compañeros que se fueron o cuya misión terminó.' },
      { key: 'QuestMates.Debug', default: '0', type: 'bool', min: null, max: null, risk: 'low', description: 'Eleva a INFO los mensajes de diagnóstico del módulo (por defecto en DEBUG).' },
      { key: 'QuestMates.StuckMinutes', default: '0', type: 'int', min: 0, max: null, risk: 'low', description: 'Soltar la reserva de un bot si una misión que el módulo le inyectó no pasa de INCOMPLETE en N minutos. 0 lo desactiva. Solo afecta a misiones inyectadas por el módulo.' },
      { key: 'QuestMates.AbandonStuck', default: '0', type: 'bool', min: null, max: null, risk: 'medium', description: 'Además de soltar la reserva, quitar la misión atascada del diario del bot. Solo misiones inyectadas por el módulo.' },
    ],
  },
  {
    id: 'module-queue-bots',
    label: 'mod-queue-bots',
    group: 'module',
    module: 'mod-queue-bots',
    file: 'mod_queue_bots.conf',
    params: [
      { key: 'QueueBots.Enable', default: '1', type: 'bool', min: null, max: null, risk: 'medium', description: 'Interruptor maestro del módulo.' },
      { key: 'QueueBots.MaxRaidBots', default: '39', type: 'int', min: 0, max: null, risk: 'medium', description: 'Mismo límite que PartyHere.MaxRaidBots, deben ir coordinados.' },
      { key: 'QueueBots.ScanIntervalMs', default: '2000', type: 'int', min: 250, max: null, risk: 'low', description: 'Milisegundos entre pasadas de rellenado de colas (el ritmo al que se revisa tu cola y se meten bots). Mínimo 250.' },
      { key: 'QueueBots.ClassVariety', default: '1', type: 'bool', min: null, max: null, risk: 'low', description: 'Evitar repetir clase en el grupo mientras haya alternativas libres. En población baja conviene apagarlo para llenar aunque se repitan.' },
      { key: 'QueueBots.BattlegroundFillToFull', default: '0', type: 'bool', min: null, max: null, risk: 'low', description: 'Llenar los campos de batalla a plantilla completa en vez de al mínimo que necesita el núcleo para arrancar.' },
      { key: 'QueueBots.Backfill', default: '1', type: 'bool', min: null, max: null, risk: 'low', description: 'Reponer con otro bot del mismo tramo y bando cuando uno se cae de un campo de batalla o arena a mitad de partida. Solo campos de batalla y arenas normales.' },
      { key: 'QueueBots.BackfillIntervalSecs', default: '20', type: 'int', min: 3, max: null, risk: 'low', description: 'Segundos entre pasadas de reposición mientras estás en la partida.' },
      { key: 'QueueBots.BackfillGiveUpSecs', default: '45', type: 'int', min: 10, max: null, risk: 'low', description: 'Un repuesto que lleva este tiempo en cola sin llegar a entrar (partida llena o a punto de acabar) se saca de la cola.' },
      { key: 'QueueBots.DungeonTanks', default: '1', type: 'int', min: 0, max: 5, risk: 'low', description: 'Tanques en el grupo de cinco del buscador de mazmorras.' },
      { key: 'QueueBots.DungeonHealers', default: '1', type: 'int', min: 0, max: 5, risk: 'low', description: 'Sanadores en el grupo de cinco del buscador de mazmorras.' },
      { key: 'QueueBots.DungeonDamage', default: '3', type: 'int', min: 0, max: 5, risk: 'low', description: 'DPS en el grupo de cinco del buscador de mazmorras.' },
      { key: 'QueueBots.DungeonClearTries', default: '3', type: 'int', min: 1, max: null, risk: 'low', description: 'Intentos de mandar ".dc on" (cada 15 s) hasta que mod-dungeon-clear tiene la mazmorra lista.' },
      { key: 'QueueBots.WakeCooldownSecs', default: '15', type: 'int', min: 1, max: null, risk: 'low', description: 'Margen entre tandas de despertar bots dormidos, por (tramo, facción).' },
      { key: 'QueueBots.RaidSummonGiveUpSecs', default: '60', type: 'int', min: 5, max: null, risk: 'low', description: 'Segundos que se intenta traer a un bot recién metido en la banda antes de dejarlo donde esté.' },
    ],
  },
  {
    id: 'module-server-help',
    label: 'mod-server-help',
    group: 'module',
    module: 'mod-server-help',
    file: 'mod_server_help.conf',
    params: [
      { key: 'ServerHelp.Enable', default: '1', type: 'bool', min: null, max: null, risk: 'low', description: 'Interruptor maestro del módulo.' },
      { key: 'ServerHelp.MaxSearchResults', default: '60', type: 'int', min: 0, max: null, risk: 'low', description: 'Resultados máximos de ".ayuda buscar".' },
      { key: 'ServerHelp.CacheSeconds', default: '300', type: 'int', min: 0, max: null, risk: 'low', description: 'Segundos de caché antes de recargar los datos.' },
      { key: 'ServerHelp.SnapshotMaxAge', default: '3600', type: 'int', min: 60, max: null, risk: 'low', description: 'Segundos que se guarda una instantánea del índice sin que nadie la use antes de descartarla.' },
      { key: 'ServerHelp.SearchQueryMaxBytes', default: '64', type: 'int', min: 8, max: null, risk: 'low', description: 'Recorte de la consulta de ".ayuda buscar" (bytes).' },
      { key: 'ServerHelp.CommandQueryMaxBytes', default: '128', type: 'int', min: 8, max: null, risk: 'low', description: 'Recorte de la ruta de ".ayuda comando" (bytes).' },
      { key: 'ServerHelp.DefaultCategory.Console', default: '0', type: 'int', min: 0, max: null, risk: 'low', description: 'Categoría para los comandos de consola. 0 usa la de Administración.' },
      { key: 'ServerHelp.RateWindowSeconds', default: '20', type: 'int', min: 1, max: null, risk: 'low', description: 'Ventana del límite por cuenta de subcomandos de ".ayuda".' },
      { key: 'ServerHelp.RateMaxPerWindow', default: '20', type: 'int', min: 0, max: null, risk: 'low', description: 'Máximo de subcomandos de ".ayuda" (índice, buscar, comando, artículo) por cuenta y ventana. 0 desactiva el límite.' },
      { key: 'ServerHelp.Export', default: '1', type: 'bool', min: null, max: null, risk: 'low', description: 'Permite que ".ayuda export" (administrador) vuelque los comandos descubiertos sin ficha propia como filas auto=1 en server_help_command, para que esta pantalla vea el árbol completo. Las fichas curadas no se tocan.' },
    ],
  },
  {
    id: 'module-update-notice',
    label: 'mod-update-notice',
    group: 'module',
    module: 'mod-update-notice',
    file: 'mod_update_notice.conf',
    params: [
      { key: 'UpdateNotice.Enable', default: '1', type: 'bool', min: null, max: null, risk: 'low', description: 'Interruptor maestro del módulo.' },
      { key: 'UpdateNotice.MinSecurity', default: '2', type: 'int', min: 0, max: null, risk: 'medium', description: 'Quién ve el aviso de actualizaciones pendientes.' },
      { key: 'UpdateNotice.MaxDaysStale', default: '10', type: 'int', min: 0, max: null, risk: 'low', description: 'Días de antigüedad del informe antes de que el aviso advierta de que la revisión semanal puede haber fallado. Con 0 no avisa de la antigüedad.' },
      { key: 'UpdateNotice.OncePerSession', default: '0', type: 'bool', min: null, max: null, risk: 'low', description: 'No repetir el aviso si la misma cuenta hace relog durante el mismo arranque del servidor. El comando lo vuelve a mostrar.' },
      { key: 'UpdateNotice.Severity', default: '1', type: 'bool', min: null, max: null, risk: 'low', description: 'Ordenar y colorear las líneas del informe por un prefijo [seguridad] / [incompat] / [funcional] / [informativo]. tools/revisar-actualizaciones.sh marca el core y los repos con parche propio como incompatibilidad.' },
      { key: 'UpdateNotice.CommandOnly', default: '0', type: 'bool', min: null, max: null, risk: 'low', description: 'Sin aviso automático al entrar; solo ".actualizaciones".' },
      { key: 'UpdateNotice.SayIfNoneOnLogin', default: '0', type: 'bool', min: null, max: null, risk: 'low', description: 'Decir "todo al día" también en el aviso de login cuando no hay novedades.' },
    ],
  },
  {
    id: 'module-world-bots',
    label: 'mod-world-bots',
    group: 'module',
    module: 'mod-world-bots',
    file: 'mod_world_bots.conf',
    params: [
      { key: 'WorldBots.Enable', default: '1', type: 'bool', min: null, max: null, risk: 'medium', description: 'Interruptor maestro de los bots de mundo.' },
      { key: 'WorldBots.MinBots', default: '12', type: 'int', min: 0, max: null, risk: 'medium', description: 'Población mínima de bots de mundo simultáneos.' },
      { key: 'WorldBots.MaxBots', default: '25', type: 'int', min: 0, max: null, risk: 'medium', description: 'Población máxima de bots de mundo simultáneos.' },
      { key: 'WorldBots.MaxTeleportsPerPass', default: '10', type: 'int', min: 0, max: null, risk: 'medium', description: 'Presupuesto global de reubicaciones y logins de bot por pasada, compartido entre todos los jugadores y zonas.' },
      { key: 'WorldBots.BotMinWorldSeconds', default: '60', type: 'int', min: 0, max: null, risk: 'low', description: 'Antigüedad mínima de una sesión bot antes de reubicarla para población o PvP.' },
      { key: 'WorldBots.Stage.SyncSeconds', default: '60', type: 'int', min: 0, max: null, risk: 'low', description: 'Intervalo para reconciliar el tope y los mapas de etapa si otra recarga de playerbots los pisa.' },
      { key: 'WorldBots.PlayerScale.Enable', default: '0', type: 'bool', min: null, max: null, risk: 'high', description: 'Pisa en caliente AiPlayerbot.MinRandomBots/MaxRandomBots con PerPlayer × jugadores reales conectados (tope Ceiling). Sin jugadores no toca nada. Al desactivarlo restaura el valor que tuviera playerbots.conf.' },
      { key: 'WorldBots.PlayerScale.PerPlayer', default: '150', type: 'int', min: 1, max: null, risk: 'high', description: 'Bots objetivo por cada jugador real conectado.' },
      { key: 'WorldBots.PlayerScale.Ceiling', default: '600', type: 'int', min: 1, max: null, risk: 'medium', description: 'Tope duro del total, aunque se conecten muchos jugadores.' },
      { key: 'WorldBots.PlayerScale.SyncSeconds', default: '60', type: 'int', min: 0, max: null, risk: 'low', description: 'Cada cuánto se recalcula el objetivo. Bajarlo no expulsa bots de golpe: sólo deja de admitir altas nuevas.' },
      { key: 'WorldBots.Verbose', default: '0', type: 'bool', min: null, max: null, risk: 'low', description: 'Eleva a INFO la actividad recurrente de población; desactivado la conserva sólo en DEBUG.' },
      { key: 'WorldBots.AdaptiveDensity', default: '0', type: 'bool', min: null, max: null, risk: 'low', description: 'Con varios humanos en una zona el objetivo de bots crece (AdaptiveDensityPerHuman por cada humano de más). Con 0 el objetivo es un valor al azar del rango MinBots-MaxBots elegido al entrar en la zona.' },
      { key: 'WorldBots.Samaritan', default: '0', type: 'bool', min: null, max: null, risk: 'medium', description: 'EXPERIMENTAL. Cuando un jugador está en combate por debajo de SamaritanHpPercent de vida, hasta SamaritanMaxHelpers bots libres cercanos se teletransportan a su lado y se ponen a cazar allí un rato (sin agruparse ni tocarle el botín). El jugador lo rechaza con ".wbots samaritano off".' },
      { key: 'WorldBots.SamaritanHpPercent', default: '35', type: 'int', min: 1, max: 99, risk: 'low', description: 'Porcentaje de vida del jugador por debajo del cual acuden bots samaritanos.' },
      { key: 'WorldBots.SamaritanMaxHelpers', default: '2', type: 'int', min: 1, max: null, risk: 'low', description: 'Máximo de bots que acuden a ayudar a un mismo jugador a la vez.' },
      { key: 'BotPopulation.PendingTimeoutSeconds', default: '90', type: 'int', min: 1, max: null, risk: 'low', description: 'Caducidad de una reserva cuyo login no llega a aparecer online.' },
      { key: 'BotPopulation.MaxPendingTotal', default: '40', type: 'int', min: 0, max: null, risk: 'medium', description: 'Máximo global de logins bot simultáneos; 0 elimina sólo este límite intermedio.' },
      { key: 'BotPopulation.MaxPendingPerFaction', default: '24', type: 'int', min: 0, max: null, risk: 'medium', description: 'Máximo de logins pendientes por facción; 0 desactiva este reparto.' },
      { key: 'BotPopulation.MaxPendingPerRange', default: '12', type: 'int', min: 0, max: null, risk: 'medium', description: 'Máximo pendiente para una misma facción y tramo de nivel; 0 lo desactiva.' },
      { key: 'WorldBots.NearbyPlayerRadius', default: '150', type: 'int', min: 50, max: null, risk: 'low', description: 'Radio de la comprobación "un jugador lo está viendo" antes de reubicar un bot; también es el suelo de MinDistance y CityMinDistance.' },
      { key: 'WorldBots.WakeBatchSeconds', default: '15', type: 'int', min: 1, max: null, risk: 'low', description: 'Margen entre tandas de despertar bots dormidos para poblar zonas.' },
      { key: 'WorldBots.ZoneSettleSeconds', default: '2', type: 'int', min: 0, max: null, risk: 'low', description: 'Espera a que la zona se asiente al cambiar de zona antes de contar y rellenar.' },
      { key: 'WorldBots.RetrySeconds', default: '15', type: 'int', min: 1, max: null, risk: 'low', description: 'Reintento de relleno cuando faltan bots libres o el teletransporte no cabe en la pasada.' },
      { key: 'WorldBots.Pvp.Enable', default: '1', type: 'bool', min: null, max: null, risk: 'medium', description: 'Activa el subsistema de PvP simulado entre bots de mundo.' },
      { key: 'WorldBots.Pvp.MinBotsToStart', default: '2', type: 'int', min: 1, max: null, risk: 'low', description: 'Mínimo de bots por bando para que una escaramuza arranque.' },
      { key: 'WorldBots.Pvp.AutoEnableHighHotspots', default: '1', type: 'bool', min: null, max: null, risk: 'low', description: 'Reactivar en automático los puntos calientes de 50-60 (SearingGorge, BlackrockMountain, LightHopeChapel) cuando hay población de ese nivel en ambas facciones.' },
      { key: 'WorldBots.Pvp.CaptureObjective', default: '1', type: 'bool', min: null, max: null, risk: 'low', description: 'El bando con más bots vivos cerca del punto suma control; al llegar al umbral captura y el evento termina antes de tiempo, con anuncio de ganador. Con 0 el evento solo acaba por duración.' },
      { key: 'WorldBots.Pvp.CaptureRadius', default: '40', type: 'int', min: 5, max: null, risk: 'low', description: 'Yardas alrededor del punto que cuentan para el control de la captura.' },
      { key: 'WorldBots.Pvp.CaptureGoal', default: '10', type: 'int', min: 1, max: null, risk: 'low', description: 'Ticks de control (uno cada ~15 s) que un bando necesita para capturar el punto.' },
      { key: 'WorldBots.Pvp.GearMode', default: '1', type: 'int', min: 0, max: 2, risk: 'low', description: 'Topar el equipo de los bots de la guerra a la fase del humano de la zona. 0 = no tocar, 1 = media + margen sin pasar del tope de fase, 2 = solo el tope de fase.' },
      { key: 'WorldBots.Pvp.KeepAwayDistance', default: '160', type: 'int', min: 0, max: null, risk: 'low', description: 'Un punto de escaramuza nunca a menos de estas yardas de un humano.' },
      { key: 'WorldBots.Pvp.RepositionDistance', default: '200', type: 'int', min: 1, max: null, risk: 'low', description: 'Distancia a la que se reproyecta un punto demasiado cerca de un humano.' },
      { key: 'WorldBots.Pvp.NearbyPlayerRadius', default: '150', type: 'int', min: 50, max: null, risk: 'low', description: 'Radio de "alguien lo está viendo" al teletransportar un bot de la guerra; si no se pone hereda WorldBots.NearbyPlayerRadius.' },
      { key: 'WorldBots.Pvp.CombatGraceSeconds', default: '60', type: 'int', min: 0, max: null, risk: 'low', description: 'Segundos que se deja a un bot acabar la pelea antes de forzarle la vuelta a casa al terminar el evento.' },
      { key: 'WorldBots.Pvp.DuelRange', default: '35', type: 'int', min: 5, max: null, risk: 'low', description: 'Distancia máxima para lanzar el hechizo de duelo.' },
      { key: 'WorldBots.Pvp.DuelMaxTries', default: '20', type: 'int', min: 1, max: null, risk: 'low', description: 'Intentos de acercar al retado antes de abandonar la pareja de duelo.' },
    ],
  },
  {
    id: 'module-standby',
    label: 'mod-standby (modo en espera)',
    group: 'module',
    module: 'mod-standby',
    file: 'mod_standby.conf',
    params: [
      { key: 'Standby.Enable', default: '1', type: 'bool', min: null, max: null, risk: 'medium', description: 'Apagar el worldserver cuando no hay jugadores humanos. Con 0 el servidor nunca se duerme solo (pero sigue arrancando por activación de socket si WORLDSERVER_STANDBY está activo).' },
      { key: 'Standby.IdleMinutes', default: '15', type: 'int', min: 1, max: 720, risk: 'low', description: 'Minutos sin ninguna sesión humana antes de apagar el worldserver.' },
      { key: 'Standby.WarnSeconds', default: '60', type: 'int', min: 0, max: 900, risk: 'low', description: 'Segundos de cuenta atrás con aviso antes de cerrar. 0 = cerrar de inmediato.' },
      { key: 'Standby.MinUptimeMinutes', default: '10', type: 'int', min: 0, max: 120, risk: 'low', description: 'El módulo no apaga el servidor durante estos minutos tras arrancar (cubre el primer arranque y da margen al jugador que lo despertó).' },
      { key: 'Standby.CheckSeconds', default: '30', type: 'int', min: 1, max: 600, risk: 'low', description: 'Cada cuántos segundos se cuenta la población humana (durante una cuenta atrás pasa a cada tick).' },
    ],
  },
];

export function findParam(key, file) {
  for (const category of CATEGORIES) {
    if (category.file !== file) continue;
    const param = category.params.find((p) => p.key === key);
    if (param) {
      return { ...param, categoryId: category.id, file: category.file, group: category.group, module: category.module };
    }
  }
  return null;
}

export function allCategories() {
  return CATEGORIES;
}
