-- Localizacion espanola para clientes esES/esMX.
-- Se aplica al mostrar cada texto para mantener intactas las claves y comandos
-- internos que espera la estructura original de MultiBot.

local locale = GetLocale()
if(locale ~= "esES" and locale ~= "esMX") then return end

local exact = {
	["Inventory"] = "Inventario",
	["Spellbook"] = "Libro de hechizos",
	["Select the Rewards"] = "Selecciona las recompensas",
	["Rank"] = "Rango",
	["Title"] = "Nombre",
	["|cff402000Rank|r"] = "|cff402000Rango|r",
	["|cffffcc00Title|r"] = "|cffffcc00Nombre|r",
	["Warrior"] = "Guerrero", ["Warlock"] = "Brujo",
	["Shaman"] = "Chaman", ["Rogue"] = "Picaro",
	["Priest"] = "Sacerdote", ["Paladin"] = "Paladin",
	["Mage"] = "Mago", ["Hunter"] = "Cazador",
	["Druid"] = "Druida", ["DeathKnight"] = "Caballero de la Muerte",
	["Attack"] = "Atacar", ["Stay"] = "Quedarse", ["Follow"] = "Seguir",
	["Flee"] = "Huir", ["Healer"] = "Sanador", ["Tank"] = "Tanque",
	["Target"] = "Objetivo", ["Actions"] = "Acciones", ["Reset"] = "Reiniciar",
	["Release"] = "Liberar", ["Stats"] = "Estadisticas", ["Reward"] = "Recompensa",
	["Summon"] = "Invocar", ["Appear"] = "Aparecer", ["Browse"] = "Explorar"
}

-- Las descripciones originales siguen una plantilla muy repetida. Estas
-- sustituciones traducen tanto los controles generales como los de clase.
local replacements = {
	{"The Execution%-Order shows the Receiver for Commandos", "El destino del comando indica quien lo recibira"},
	{"With this Control you can give the Command to attack", "Con este control puedes ordenar un ataque"},
	{"With this Control you can give the Command to flee", "Con este control puedes ordenar una retirada"},
	{"Right%-Click the Options to define a new default Action", "Haz clic derecho en una opcion para convertirla en la accion predeterminada"},
	{"Left%-Click the Options to select another Combat%-Mode", "Haz clic izquierdo en una opcion para seleccionar otro modo de combate"},
	{"This Control allows you to switch a Combat%-Mode on and off", "Este control permite activar o desactivar un modo de combate"},
	{"This Control allows you to change the Formation of your Bots", "Este control permite cambiar la formacion de tus bots"},
	{"With this Button the Tanks starting to attack your target", "Con este boton los tanques atacan a tu objetivo"},
	{"With this Command the hole Raid or Party starting to attack your target", "Con este comando toda la banda o el grupo ataca a tu objetivo"},
	{"With this Command the Ranged%-Fighters starting to attack your target", "Con este comando los combatientes a distancia atacan a tu objetivo"},
	{"With this Command the Melee%-Fighters starting to attack your target", "Con este comando los combatientes cuerpo a cuerpo atacan a tu objetivo"},
	{"With this Command the Healers starting to attack your target", "Con este comando los sanadores atacan a tu objetivo"},
	{"With this Command the DPS starting to attack your target", "Con este comando los DPS atacan a tu objetivo"},
	{"With this Command the Tanks starting to attack your target", "Con este comando los tanques atacan a tu objetivo"},
	{"With this Command the hole Raid or Party starting to flee", "Con este comando toda la banda o el grupo se retira"},
	{"With this Command the Ranged%-Fighters starting to flee", "Con este comando los combatientes a distancia se retiran"},
	{"With this Command the Melee%-Fighters starting to flee", "Con este comando los combatientes cuerpo a cuerpo se retiran"},
	{"With this Command the Healers starting to flee", "Con este comando los sanadores se retiran"},
	{"With this Command the DPS starting to flee", "Con este comando los DPS se retiran"},
	{"With this Command the Tanks starting to flee", "Con este comando los tanques se retiran"},
	{"With this Command the Target starting to flee", "Con este comando el objetivo se retira"},
	{"In the Passive%-Mode, your Bots wont attack any Opponent", "En modo pasivo, tus bots no atacaran a ningun enemigo"},
	{"In the Grind%-Mode, your Bots attack each Opponent at random", "En modo agresivo, tus bots atacan enemigos al azar"},
	{"This Mode is useful to keep the Tank from running into the Opponents during a pull", "Este modo evita que el tanque se lance contra los enemigos durante una atraccion"},
	{"This Mode is usefull if you under attack of to much Opponents", "Este modo es util cuando te atacan demasiados enemigos"},
	{"With this Button you can give right now the Command to Stay", "Con este boton ordenas quedarse en el sitio"},
	{"With this Button you can give right now the Command to Follow", "Con este boton ordenas que te sigan"},
	{"The Bots line up in an arrow formation", "Los bots se colocan en formacion de flecha"},
	{"The Bots line up in an defensive formation", "Los bots se colocan en formacion defensiva"},
	{"The Bots line up near by", "Los bots se colocan cerca"},
	{"The Bots line up for melee fights", "Los bots se colocan para el combate cuerpo a cuerpo"},
	{"The Bots line up on the left and right side in a parallel line", "Los bots se colocan en lineas paralelas a izquierda y derecha"},
	{"The Bots line up in a circle around you", "Los bots forman un circulo a tu alrededor"},
	{"The Bots line of sight is in your direction", "Los bots miran en tu direccion"},
	{"The Bots line of sight is directed outwards", "Los bots miran hacia fuera"},
	{"Each Bot follows you by its own", "Cada bot te sigue de manera independiente"},
	{"In the DPS%-Control you will find the general DPS%-Strategies", "En el control de DPS encontraras las estrategias generales de DPS"},
	{"In the Playbook you will find the Strategies typical for the Class", "En la configuracion encontraras las estrategias propias de la clase"},
	{"This Control allows you to select, enable or disable the default", "Este control permite seleccionar, activar o desactivar el"},
	{"Bear, Cat, Caster and Heal are mutually exclusive", "Oso, felino, taumaturgo y sanacion son mutuamente excluyentes"},
	{"Caster, Melee and Heal are mutually exclusive", "Taumaturgo, cuerpo a cuerpo y sanacion son mutuamente excluyentes"},
	{"DPS and Tank are mutually exclusive", "DPS y tanque son mutuamente excluyentes"},
	{"Tank, DPS and Heal are mutually exclusive", "Tanque, DPS y sanacion son mutuamente excluyentes"},
	{"Arcane%-, Frost%- and Fire%-Magic are mutually exclusive", "Las magias arcana, de escarcha y de fuego son mutuamente excluyentes"},
	{"Shadow and Heal are mutually exclusive", "Sombras y sanacion son mutuamente excluyentes"},
	{"Right%-Click to drag and move", "Clic derecho y arrastra para mover"},
	{"Left%-Click", "Clic izquierdo"}, {"Right%-Click", "Clic derecho"},
	{"Execution%-Order:", "Destino del comando:"},
	{"Raid, Party", "Banda, Grupo"}, {"System", "Sistema"}, {"Target", "Objetivo"},
	{"to show or hide", "para mostrar u ocultar"},
	{"to enable or disable", "para activar o desactivar"},
	{"to select and activate", "para seleccionar y activar"},
	{"to selet and activate", "para seleccionar y activar"},
	{"to define as default Action", "para establecer como accion predeterminada"},
	{"to execute the default Action", "para ejecutar la accion predeterminada"},
	{"to execute", "para ejecutar"}, {"to select", "para seleccionar"},
	{"to create", "para crear"}, {"to filter for", "para filtrar"},
	{"to reset", "para reiniciar"}, {"to open or close", "para abrir o cerrar"},
	{"to open", "para abrir"}, {"to close", "para cerrar"},
	{"to add", "para anadir"}, {"to remove", "para quitar"},
	{"to summon", "para invocar"}, {"to appear", "para aparecer"},
	{"With this Button", "Con este boton"}, {"With this Command", "Con este comando"},
	{"With this Control", "Con este control"}, {"This Control", "Este control"},
	{"This Button", "Este boton"}, {"this Button", "este boton"},
	{"In this Control you will find", "En este control encontraras"},
	{"In this Box you will find", "En este panel encontraras"},
	{"Allows the", "Permite al"}, {" to use ", " usar "},
	{" during the Combat", " durante el combate"},
	{"It allows the", "Permite al"}, {"It makes the", "Convierte al"},
	{" to Buff the Group", " mejorar al grupo"}, {" to the Healer of the Group", " en el sanador del grupo"},
	{"It opens or closes the", "Abre o cierra el"},
	{"Invites this Bot to your Group", "Invita este bot a tu grupo"},
	{"Dismiss this Bot from your Group", "Expulsa este bot de tu grupo"},
	{"Summons this Bot to your Position", "Invoca este bot en tu posicion"},
	{"The Buttonbars will appear after adding the Bot", "Las barras apareceran despues de anadir el bot"},
	{"The Stretegies can be configured with the Buttonbars on the left and right side", "Las estrategias se configuran con las barras de los lados izquierdo y derecho"},
	{"This Button adds or removes NAME to or from your Group", "Este boton anade o quita a NAME de tu grupo"},
	{"switches the Selfbot%-Mode on and off", "activa o desactiva el modo Selfbot"},
	{"Left%-Click the Spell to cast it immediately", "Haz clic izquierdo en el hechizo para lanzarlo al instante"},
	{"Right%-Click the Spell to pickup a Macro for your Hotbars", "Haz clic derecho en el hechizo para crear una macro en tus barras"},
	{"It enables the", "Activa las"}, {"It disables the", "Desactiva las"},
	{"It enables or disables the", "Activa o desactiva las"},
	{"It allows", "Permite"}, {"It will", "Va a"},
	{"Only one of these Strategies can be activated", "Solo se puede activar una de estas estrategias"},
	{"are mutually exclusive", "son mutuamente excluyentes"},
	{"Combat%-Strategies", "estrategias de combate"},
	{"Non%-Combat%-Strategies", "estrategias fuera de combate"},
	{"Strategies", "estrategias"}, {"Strategy", "estrategia"},
	{"Options", "opciones"}, {"Commandos", "comandos"}, {"Commands", "comandos"},
	{"your target", "tu objetivo"}, {"your Target", "tu objetivo"},
	{"your Group", "tu grupo"}, {"your Bots", "tus bots"}, {"the Bots", "los bots"},
	{"the Group", "el grupo"}, {"the Roster", "la lista"},
	{"Playerbot%-Roster", "lista de Playerbot"}, {"Guild%-Roster", "lista de hermandad"},
	{"Friend%-Roster", "lista de amigos"}, {"Active%-Roster", "lista de activos"},
	{"Attack%-Control", "Control de ataque"}, {"Flee%-Control", "Control de huida"},
	{"Formation%-Control", "Control de formacion"}, {"Mode%-Control", "Control de modo"},
	{"Main%-Control", "Control principal"}, {"GameMaster%-Control", "Control de maestro de juego"},
	{"Creator%-Control", "Control de creacion"}, {"Invite%-Control", "Control de invitacion"},
	{"DPS%-Control", "Control de DPS"}, {"Playbook%-Control", "Control de configuracion"},
	{"Passive%-Mode", "Modo pasivo"}, {"Grind%-Mode", "Modo agresivo"},
	{"Arrow%-Formation", "Formacion en flecha"}, {"Queue%-Formation", "Formacion en fila"},
	{"Near%-Formation", "Formacion cercana"}, {"Melee%-Formation", "Formacion cuerpo a cuerpo"},
	{"Line%-Formation", "Formacion en linea"}, {"Circle%-Formation", "Formacion en circulo"},
	{"Chaos%-Formation", "Formacion caotica"}, {"Shield%-Formation", "Formacion en escudo"},
	{"Ranged%-Fighters", "combatientes a distancia"}, {"Melee%-Fighters", "combatientes cuerpo a cuerpo"},
	{"Healers", "sanadores"}, {"Tanks", "tanques"}, {"Opponents", "enemigos"},
	{"Food", "Comida"}, {"Gather", "Recoleccion"}, {"Loot", "Botin"},
	{"Buff", "Mejora"}, {"Debuff", "Perjuicio"}, {"Presence", "Presencia"},
	{"Seal", "Sello"}, {"Totem", "Totem"}, {"Aura", "Aura"},
	{"Fire", "Fuego"}, {"Frost", "Escarcha"}, {"Shadow", "Sombras"}, {"Arcane", "Arcano"},
	{"Health", "Salud"}, {"Mana", "Mana"}, {"Armor", "Armadura"}, {"Speed", "Velocidad"},
	{"Inventory", "Inventario"}, {"Spellbook", "Libro de hechizos"},
	{"Reward%-Selector", "selector de recompensas"}, {"Memory%-Portal", "Portal de memoria"},
	{"Memory%-Gem", "Gema de memoria"}, {"Location", "ubicacion"},
	{"GameMaster%-Rights", "permisos de maestro de juego"},
	{"Level%-Filter", "Filtro de nivel"}, {"Class%-Filter", "Filtro de clase"},
	{"Quality", "calidad"}, {"Slot", "casilla"}, {"Items", "objetos"}, {"Item", "objeto"},
	{"Level", "Nivel"}, {"Group", "Grupo"}, {"Party", "Grupo"}, {"Raid", "Banda"},
	{"Attack", "Ataque"}, {"Flee", "Huida"}, {"Follow", "Seguir"}, {"Stay", "Quedarse"},
	{"Heal", "Sanar"}, {"Tank", "Tanque"}, {"Ranged", "A distancia"}, {"Melee", "Cuerpo a cuerpo"},
	{"Death Knight", "Caballero de la Muerte"}, {"Druid", "Druida"}, {"Hunter", "Cazador"},
	{"Mage", "Mago"}, {"Paladin", "Paladin"}, {"Priest", "Sacerdote"},
	{"Rogue", "Picaro"}, {"Shaman", "Chaman"}, {"Warlock", "Brujo"}, {"Warrior", "Guerrero"}
}

MultiBot.LocalizeText = function(text)
	if(text == nil) then return text end
	if(exact[text] ~= nil) then return exact[text] end
	text = string.gsub(text, "Inventory of ", "Inventario de ")
	text = string.gsub(text, "Spellbook of ", "Libro de hechizos de ")
	return text
end

MultiBot.LocalizeTip = function(text)
	if(text == nil) then return text end
	for _, replacement in ipairs(replacements) do
		text = string.gsub(text, replacement[1], replacement[2])
	end
	return text
end
